mv /optdata/ocapp/sftp_mount/ocftpuser/*.csv  /home/ocftpuser/
mv /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/inbox/digital_receipt/*.zip /home/ocftpuser/opt_sync/inbox/digital_receipt/
mv /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/inbox/loyalty/enroll/*.zip /home/ocftpuser/opt_sync/inbox/loyalty/enroll/  
mv /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/inbox/loyalty/issuance/*.zip /home/ocftpuser/opt_sync/inbox/loyalty/issuance/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_7999133388222750* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_8210100496601905* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_8926919240006477* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_5297765320155573* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_7003511119527909* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_5246720266877283* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_1298584195420544* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_2767207794111799* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_3487686673963318* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_6023234776961715* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_3389872975908664* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_9358585677987003* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_9899340603342089* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_3100518656282973* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_8331971569591439* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_6732439233020827* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_8920464665893486* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_2600187455283812* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_1851724308315104* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_3629694461518643* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_7742626867535656* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_1342700599285694* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
mv /home/ocftpuser/opt_sync/outbox/loyalty/enroll/Loyalty_Enroll_6637248297152324* /optdata/ocapp/sftp_mount/ocftpuser/opt_sync/outbox/loyalty/enroll/
