package org.mq.captiway.scheduler.beans;
// Generated 3 Jul, 2009 10:14:21 AM by Hibernate Tools 3.2.0.CR1



/**
 * MLCustomFields generated by hbm2java
 */
@SuppressWarnings("serial")
public class MLCustomFields  implements java.io.Serializable {


     private Long cId;
     private String selectedField;
     private int fieldIndex;
     private String custFieldName;
     private String dataType;
     private String defaultValue;
     private MailingList mailingList;
     private String format;
     
    public MLCustomFields() {
    }

	
    public MLCustomFields(MailingList mailingList) {
        this.mailingList = mailingList;
    }
    public MLCustomFields(String selectedField, int fieldIndex, String custFieldName, String dataType, MailingList mailingList) {
       this.selectedField = selectedField;
       this.fieldIndex = fieldIndex;
       this.custFieldName = custFieldName;
       this.dataType = dataType;
       this.mailingList = mailingList;
    }
   
    public Long getcId() {
        return this.cId;
    }
    
    public void setcId(Long cId) {
        this.cId = cId;
    }
    public String getSelectedField() {
        return this.selectedField;
    }
    
    public void setSelectedField(String selectedField) {
        this.selectedField = selectedField;
    }
    public int getFieldIndex() {
        return this.fieldIndex;
    }
    
    public void setFieldIndex(int fieldIndex) {
        this.fieldIndex = fieldIndex;
    }
    public String getCustFieldName() {
        return this.custFieldName;
    }
    
    public void setCustFieldName(String custFieldName) {
        this.custFieldName = custFieldName;
    }
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    public String getDefaultValue() {
		return defaultValue;
	}


	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}


	public MailingList getMailingList() {
        return this.mailingList;
    }
    
    public void setMailingList(MailingList mailingList) {
        this.mailingList = mailingList;
    }


	public String getFormat() {
		return format;
	}


	public void setFormat(String format) {
		this.format = format;
	}
}

