package org.mq.captiway.scheduler.beans;
// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;
import java.util.Date;

/**
 * MyTemplates generated by hbm2java
 */

public class MyTemplates  implements java.io.Serializable {


     private Long myTemplateId;
     private String name;
     private String content;
     private Calendar createdDate;
     private String editorType;
     private Users users;

     
     private String folderName;

     public String getFolderName() {
 		return folderName;
 	}


 	public void setFolderName(String folderName) {
 		this.folderName = folderName;
 	}
 	
    public MyTemplates() {
    }

	
    public MyTemplates(String name, String editorType) {
        this.name = name;
        this.editorType = editorType;
    }
    public MyTemplates(String name, String content, Date date, String editorType, Users users) {
       this.name = name;
       this.content = content;
       this.createdDate = createdDate;
       this.editorType = editorType;
       this.users = users;
    }
   
    public Long getMyTemplateId() {
        return this.myTemplateId;
    }
    
    public void setMyTemplateId(Long myTemplateId) {
        this.myTemplateId = myTemplateId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    public String getEditorType() {
        return this.editorType;
    }
    
    public void setEditorType(String editorType) {
        this.editorType = editorType;
    }
    
 
	public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

}


