
package org.mq.marketer.sparkbase.sparkbaseAdminWsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SparkbaseAdminV45WsdlPort", targetNamespace = "urn:SparkbaseAdminV45Wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SparkbaseAdminV45WsdlPort {


    /**
     * 
     * @param accountAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.AccountAddResponse
     */
    @WebMethod(operationName = "AccountAdd")
    @WebResult(name = "AccountAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountAddResponse")
    public AccountAddResponse accountAdd(
        @WebParam(name = "AccountAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountAdd")
        AccountAdd accountAdd);

    /**
     * 
     * @param accountEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.AccountEditResponse
     */
    @WebMethod(operationName = "AccountEdit")
    @WebResult(name = "AccountEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountEditResponse")
    public AccountEditResponse accountEdit(
        @WebParam(name = "AccountEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountEdit")
        AccountEdit accountEdit);

    /**
     * 
     * @param accountsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.AccountsViewResponse
     */
    @WebMethod(operationName = "AccountsView")
    @WebResult(name = "AccountsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountsViewResponse")
    public AccountsViewResponse accountsView(
        @WebParam(name = "AccountsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountsView")
        AccountsView accountsView);

    /**
     * 
     * @param accountsQueue
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.AccountsQueueResponse
     */
    @WebMethod(operationName = "AccountsQueue")
    @WebResult(name = "AccountsQueueResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountsQueueResponse")
    public AccountsQueueResponse accountsQueue(
        @WebParam(name = "AccountsQueue", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "AccountsQueue")
        AccountsQueue accountsQueue);

    /**
     * 
     * @param actionAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ActionAddResponse
     */
    @WebMethod(operationName = "ActionAdd")
    @WebResult(name = "ActionAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ActionAddResponse")
    public ActionAddResponse actionAdd(
        @WebParam(name = "ActionAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ActionAdd")
        ActionAdd actionAdd);

    /**
     * 
     * @param actionEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ActionEditResponse
     */
    @WebMethod(operationName = "ActionEdit")
    @WebResult(name = "ActionEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ActionEditResponse")
    public ActionEditResponse actionEdit(
        @WebParam(name = "ActionEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ActionEdit")
        ActionEdit actionEdit);

    /**
     * 
     * @param actionsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ActionsViewResponse
     */
    @WebMethod(operationName = "ActionsView")
    @WebResult(name = "ActionsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ActionsViewResponse")
    public ActionsViewResponse actionsView(
        @WebParam(name = "ActionsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ActionsView")
        ActionsView actionsView);

    /**
     * 
     * @param balancesView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.BalancesViewResponse
     */
    @WebMethod(operationName = "BalancesView")
    @WebResult(name = "BalancesViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "BalancesViewResponse")
    public BalancesViewResponse balancesView(
        @WebParam(name = "BalancesView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "BalancesView")
        BalancesView balancesView);

    /**
     * 
     * @param cardEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CardEditResponse
     */
    @WebMethod(operationName = "CardEdit")
    @WebResult(name = "CardEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardEditResponse")
    public CardEditResponse cardEdit(
        @WebParam(name = "CardEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardEdit")
        CardEdit cardEdit);

    /**
     * 
     * @param cardsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CardsViewResponse
     */
    @WebMethod(operationName = "CardsView")
    @WebResult(name = "CardsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardsViewResponse")
    public CardsViewResponse cardsView(
        @WebParam(name = "CardsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardsView")
        CardsView cardsView);

    /**
     * 
     * @param cardSetAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CardSetAddResponse
     */
    @WebMethod(operationName = "CardSetAdd")
    @WebResult(name = "CardSetAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardSetAddResponse")
    public CardSetAddResponse cardSetAdd(
        @WebParam(name = "CardSetAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardSetAdd")
        CardSetAdd cardSetAdd);

    /**
     * 
     * @param cardSetEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CardSetEditResponse
     */
    @WebMethod(operationName = "CardSetEdit")
    @WebResult(name = "CardSetEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardSetEditResponse")
    public CardSetEditResponse cardSetEdit(
        @WebParam(name = "CardSetEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardSetEdit")
        CardSetEdit cardSetEdit);

    /**
     * 
     * @param cardSetsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CardSetsViewResponse
     */
    @WebMethod(operationName = "CardSetsView")
    @WebResult(name = "CardSetsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardSetsViewResponse")
    public CardSetsViewResponse cardSetsView(
        @WebParam(name = "CardSetsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CardSetsView")
        CardSetsView cardSetsView);

    /**
     * 
     * @param customerAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CustomerAddResponse
     */
    @WebMethod(operationName = "CustomerAdd")
    @WebResult(name = "CustomerAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomerAddResponse")
    public CustomerAddResponse customerAdd(
        @WebParam(name = "CustomerAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomerAdd")
        CustomerAdd customerAdd);

    /**
     * 
     * @param customerEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CustomerEditResponse
     */
    @WebMethod(operationName = "CustomerEdit")
    @WebResult(name = "CustomerEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomerEditResponse")
    public CustomerEditResponse customerEdit(
        @WebParam(name = "CustomerEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomerEdit")
        CustomerEdit customerEdit);

    /**
     * 
     * @param customerRemove
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CustomerRemoveResponse
     */
    @WebMethod(operationName = "CustomerRemove")
    @WebResult(name = "CustomerRemoveResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomerRemoveResponse")
    public CustomerRemoveResponse customerRemove(
        @WebParam(name = "CustomerRemove", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomerRemove")
        CustomerRemove customerRemove);

    /**
     * 
     * @param customersView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CustomersViewResponse
     */
    @WebMethod(operationName = "CustomersView")
    @WebResult(name = "CustomersViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomersViewResponse")
    public CustomersViewResponse customersView(
        @WebParam(name = "CustomersView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomersView")
        CustomersView customersView);

    /**
     * 
     * @param customersQueue
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.CustomersQueueResponse
     */
    @WebMethod(operationName = "CustomersQueue")
    @WebResult(name = "CustomersQueueResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomersQueueResponse")
    public CustomersQueueResponse customersQueue(
        @WebParam(name = "CustomersQueue", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "CustomersQueue")
        CustomersQueue customersQueue);

    /**
     * 
     * @param employeeAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.EmployeeAddResponse
     */
    @WebMethod(operationName = "EmployeeAdd")
    @WebResult(name = "EmployeeAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeeAddResponse")
    public EmployeeAddResponse employeeAdd(
        @WebParam(name = "EmployeeAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeeAdd")
        EmployeeAdd employeeAdd);

    /**
     * 
     * @param employeeEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.EmployeeEditResponse
     */
    @WebMethod(operationName = "EmployeeEdit")
    @WebResult(name = "EmployeeEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeeEditResponse")
    public EmployeeEditResponse employeeEdit(
        @WebParam(name = "EmployeeEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeeEdit")
        EmployeeEdit employeeEdit);

    /**
     * 
     * @param employeeRemove
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.EmployeeRemoveResponse
     */
    @WebMethod(operationName = "EmployeeRemove")
    @WebResult(name = "EmployeeRemoveResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeeRemoveResponse")
    public EmployeeRemoveResponse employeeRemove(
        @WebParam(name = "EmployeeRemove", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeeRemove")
        EmployeeRemove employeeRemove);

    /**
     * 
     * @param employeesView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.EmployeesViewResponse
     */
    @WebMethod(operationName = "EmployeesView")
    @WebResult(name = "EmployeesViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeesViewResponse")
    public EmployeesViewResponse employeesView(
        @WebParam(name = "EmployeesView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "EmployeesView")
        EmployeesView employeesView);

    /**
     * 
     * @param groupAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.GroupAddResponse
     */
    @WebMethod(operationName = "GroupAdd")
    @WebResult(name = "GroupAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "GroupAddResponse")
    public GroupAddResponse groupAdd(
        @WebParam(name = "GroupAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "GroupAdd")
        GroupAdd groupAdd);

    /**
     * 
     * @param groupEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.GroupEditResponse
     */
    @WebMethod(operationName = "GroupEdit")
    @WebResult(name = "GroupEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "GroupEditResponse")
    public GroupEditResponse groupEdit(
        @WebParam(name = "GroupEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "GroupEdit")
        GroupEdit groupEdit);

    /**
     * 
     * @param groupsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.GroupsViewResponse
     */
    @WebMethod(operationName = "GroupsView")
    @WebResult(name = "GroupsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "GroupsViewResponse")
    public GroupsViewResponse groupsView(
        @WebParam(name = "GroupsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "GroupsView")
        GroupsView groupsView);

    /**
     * 
     * @param locationAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationAddResponse
     */
    @WebMethod(operationName = "LocationAdd")
    @WebResult(name = "LocationAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationAddResponse")
    public LocationAddResponse locationAdd(
        @WebParam(name = "LocationAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationAdd")
        LocationAdd locationAdd);

    /**
     * 
     * @param locationEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationEditResponse
     */
    @WebMethod(operationName = "LocationEdit")
    @WebResult(name = "LocationEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationEditResponse")
    public LocationEditResponse locationEdit(
        @WebParam(name = "LocationEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationEdit")
        LocationEdit locationEdit);

    /**
     * 
     * @param locationsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationsViewResponse
     */
    @WebMethod(operationName = "LocationsView")
    @WebResult(name = "LocationsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationsViewResponse")
    public LocationsViewResponse locationsView(
        @WebParam(name = "LocationsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationsView")
        LocationsView locationsView);

    /**
     * 
     * @param locationsQueue
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationsQueueResponse
     */
    @WebMethod(operationName = "LocationsQueue")
    @WebResult(name = "LocationsQueueResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationsQueueResponse")
    public LocationsQueueResponse locationsQueue(
        @WebParam(name = "LocationsQueue", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationsQueue")
        LocationsQueue locationsQueue);

    /**
     * 
     * @param locationGroupAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationGroupAddResponse
     */
    @WebMethod(operationName = "LocationGroupAdd")
    @WebResult(name = "LocationGroupAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupAddResponse")
    public LocationGroupAddResponse locationGroupAdd(
        @WebParam(name = "LocationGroupAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupAdd")
        LocationGroupAdd locationGroupAdd);

    /**
     * 
     * @param locationGroupEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationGroupEditResponse
     */
    @WebMethod(operationName = "LocationGroupEdit")
    @WebResult(name = "LocationGroupEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupEditResponse")
    public LocationGroupEditResponse locationGroupEdit(
        @WebParam(name = "LocationGroupEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupEdit")
        LocationGroupEdit locationGroupEdit);

    /**
     * 
     * @param locationGroupRemove
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationGroupRemoveResponse
     */
    @WebMethod(operationName = "LocationGroupRemove")
    @WebResult(name = "LocationGroupRemoveResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupRemoveResponse")
    public LocationGroupRemoveResponse locationGroupRemove(
        @WebParam(name = "LocationGroupRemove", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupRemove")
        LocationGroupRemove locationGroupRemove);

    /**
     * 
     * @param locationGroupsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationGroupsViewResponse
     */
    @WebMethod(operationName = "LocationGroupsView")
    @WebResult(name = "LocationGroupsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupsViewResponse")
    public LocationGroupsViewResponse locationGroupsView(
        @WebParam(name = "LocationGroupsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationGroupsView")
        LocationGroupsView locationGroupsView);

    /**
     * 
     * @param locationProgramAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationProgramAddResponse
     */
    @WebMethod(operationName = "LocationProgramAdd")
    @WebResult(name = "LocationProgramAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramAddResponse")
    public LocationProgramAddResponse locationProgramAdd(
        @WebParam(name = "LocationProgramAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramAdd")
        LocationProgramAdd locationProgramAdd);

    /**
     * 
     * @param locationProgramEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationProgramEditResponse
     */
    @WebMethod(operationName = "LocationProgramEdit")
    @WebResult(name = "LocationProgramEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramEditResponse")
    public LocationProgramEditResponse locationProgramEdit(
        @WebParam(name = "LocationProgramEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramEdit")
        LocationProgramEdit locationProgramEdit);

    /**
     * 
     * @param locationProgramRemove
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationProgramRemoveResponse
     */
    @WebMethod(operationName = "LocationProgramRemove")
    @WebResult(name = "LocationProgramRemoveResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramRemoveResponse")
    public LocationProgramRemoveResponse locationProgramRemove(
        @WebParam(name = "LocationProgramRemove", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramRemove")
        LocationProgramRemove locationProgramRemove);

    /**
     * 
     * @param locationProgramsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.LocationProgramsViewResponse
     */
    @WebMethod(operationName = "LocationProgramsView")
    @WebResult(name = "LocationProgramsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramsViewResponse")
    public LocationProgramsViewResponse locationProgramsView(
        @WebParam(name = "LocationProgramsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "LocationProgramsView")
        LocationProgramsView locationProgramsView);

    /**
     * 
     * @param offerAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.OfferAddResponse
     */
    @WebMethod(operationName = "OfferAdd")
    @WebResult(name = "OfferAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "OfferAddResponse")
    public OfferAddResponse offerAdd(
        @WebParam(name = "OfferAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "OfferAdd")
        OfferAdd offerAdd);

    /**
     * 
     * @param offersView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.OffersViewResponse
     */
    @WebMethod(operationName = "OffersView")
    @WebResult(name = "OffersViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "OffersViewResponse")
    public OffersViewResponse offersView(
        @WebParam(name = "OffersView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "OffersView")
        OffersView offersView);

    /**
     * 
     * @param programAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ProgramAddResponse
     */
    @WebMethod(operationName = "ProgramAdd")
    @WebResult(name = "ProgramAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ProgramAddResponse")
    public ProgramAddResponse programAdd(
        @WebParam(name = "ProgramAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ProgramAdd")
        ProgramAdd programAdd);

    /**
     * 
     * @param programEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ProgramEditResponse
     */
    @WebMethod(operationName = "ProgramEdit")
    @WebResult(name = "ProgramEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ProgramEditResponse")
    public ProgramEditResponse programEdit(
        @WebParam(name = "ProgramEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ProgramEdit")
        ProgramEdit programEdit);

    /**
     * 
     * @param programsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ProgramsViewResponse
     */
    @WebMethod(operationName = "ProgramsView")
    @WebResult(name = "ProgramsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ProgramsViewResponse")
    public ProgramsViewResponse programsView(
        @WebParam(name = "ProgramsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ProgramsView")
        ProgramsView programsView);

    /**
     * 
     * @param promoActionAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromoActionAddResponse
     */
    @WebMethod(operationName = "PromoActionAdd")
    @WebResult(name = "PromoActionAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoActionAddResponse")
    public PromoActionAddResponse promoActionAdd(
        @WebParam(name = "PromoActionAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoActionAdd")
        PromoActionAdd promoActionAdd);

    /**
     * 
     * @param promoActionRemove
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromoActionRemoveResponse
     */
    @WebMethod(operationName = "PromoActionRemove")
    @WebResult(name = "PromoActionRemoveResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoActionRemoveResponse")
    public PromoActionRemoveResponse promoActionRemove(
        @WebParam(name = "PromoActionRemove", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoActionRemove")
        PromoActionRemove promoActionRemove);

    /**
     * 
     * @param promoActionsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromoActionsViewResponse
     */
    @WebMethod(operationName = "PromoActionsView")
    @WebResult(name = "PromoActionsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoActionsViewResponse")
    public PromoActionsViewResponse promoActionsView(
        @WebParam(name = "PromoActionsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoActionsView")
        PromoActionsView promoActionsView);

    /**
     * 
     * @param promoAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromoAddResponse
     */
    @WebMethod(operationName = "PromoAdd")
    @WebResult(name = "PromoAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoAddResponse")
    public PromoAddResponse promoAdd(
        @WebParam(name = "PromoAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoAdd")
        PromoAdd promoAdd);

    /**
     * 
     * @param promoEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromoEditResponse
     */
    @WebMethod(operationName = "PromoEdit")
    @WebResult(name = "PromoEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoEditResponse")
    public PromoEditResponse promoEdit(
        @WebParam(name = "PromoEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoEdit")
        PromoEdit promoEdit);

    /**
     * 
     * @param promosView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromosViewResponse
     */
    @WebMethod(operationName = "PromosView")
    @WebResult(name = "PromosViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromosViewResponse")
    public PromosViewResponse promosView(
        @WebParam(name = "PromosView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromosView")
        PromosView promosView);

    /**
     * 
     * @param promoCodeAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromoCodeAddResponse
     */
    @WebMethod(operationName = "PromoCodeAdd")
    @WebResult(name = "PromoCodeAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoCodeAddResponse")
    public PromoCodeAddResponse promoCodeAdd(
        @WebParam(name = "PromoCodeAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoCodeAdd")
        PromoCodeAdd promoCodeAdd);

    /**
     * 
     * @param promoCodesView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.PromoCodesViewResponse
     */
    @WebMethod(operationName = "PromoCodesView")
    @WebResult(name = "PromoCodesViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoCodesViewResponse")
    public PromoCodesViewResponse promoCodesView(
        @WebParam(name = "PromoCodesView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "PromoCodesView")
        PromoCodesView promoCodesView);

    /**
     * 
     * @param questionAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.QuestionAddResponse
     */
    @WebMethod(operationName = "QuestionAdd")
    @WebResult(name = "QuestionAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "QuestionAddResponse")
    public QuestionAddResponse questionAdd(
        @WebParam(name = "QuestionAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "QuestionAdd")
        QuestionAdd questionAdd);

    /**
     * 
     * @param questionEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.QuestionEditResponse
     */
    @WebMethod(operationName = "QuestionEdit")
    @WebResult(name = "QuestionEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "QuestionEditResponse")
    public QuestionEditResponse questionEdit(
        @WebParam(name = "QuestionEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "QuestionEdit")
        QuestionEdit questionEdit);

    /**
     * 
     * @param questionsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.QuestionsViewResponse
     */
    @WebMethod(operationName = "QuestionsView")
    @WebResult(name = "QuestionsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "QuestionsViewResponse")
    public QuestionsViewResponse questionsView(
        @WebParam(name = "QuestionsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "QuestionsView")
        QuestionsView questionsView);

    /**
     * 
     * @param storedValSettingAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.StoredValSettingAddResponse
     */
    @WebMethod(operationName = "StoredValSettingAdd")
    @WebResult(name = "StoredValSettingAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "StoredValSettingAddResponse")
    public StoredValSettingAddResponse storedValSettingAdd(
        @WebParam(name = "StoredValSettingAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "StoredValSettingAdd")
        StoredValSettingAdd storedValSettingAdd);

    /**
     * 
     * @param storedValSettingEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.StoredValSettingEditResponse
     */
    @WebMethod(operationName = "StoredValSettingEdit")
    @WebResult(name = "StoredValSettingEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "StoredValSettingEditResponse")
    public StoredValSettingEditResponse storedValSettingEdit(
        @WebParam(name = "StoredValSettingEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "StoredValSettingEdit")
        StoredValSettingEdit storedValSettingEdit);

    /**
     * 
     * @param storedValSettingsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.StoredValSettingsViewResponse
     */
    @WebMethod(operationName = "StoredValSettingsView")
    @WebResult(name = "StoredValSettingsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "StoredValSettingsViewResponse")
    public StoredValSettingsViewResponse storedValSettingsView(
        @WebParam(name = "StoredValSettingsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "StoredValSettingsView")
        StoredValSettingsView storedValSettingsView);

    /**
     * 
     * @param terminalAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.TerminalAddResponse
     */
    @WebMethod(operationName = "TerminalAdd")
    @WebResult(name = "TerminalAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalAddResponse")
    public TerminalAddResponse terminalAdd(
        @WebParam(name = "TerminalAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalAdd")
        TerminalAdd terminalAdd);

    /**
     * 
     * @param terminalEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.TerminalEditResponse
     */
    @WebMethod(operationName = "TerminalEdit")
    @WebResult(name = "TerminalEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalEditResponse")
    public TerminalEditResponse terminalEdit(
        @WebParam(name = "TerminalEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalEdit")
        TerminalEdit terminalEdit);

    /**
     * 
     * @param terminalsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.TerminalsViewResponse
     */
    @WebMethod(operationName = "TerminalsView")
    @WebResult(name = "TerminalsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalsViewResponse")
    public TerminalsViewResponse terminalsView(
        @WebParam(name = "TerminalsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalsView")
        TerminalsView terminalsView);

    /**
     * 
     * @param terminalTypesView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.TerminalTypesViewResponse
     */
    @WebMethod(operationName = "TerminalTypesView")
    @WebResult(name = "TerminalTypesViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalTypesViewResponse")
    public TerminalTypesViewResponse terminalTypesView(
        @WebParam(name = "TerminalTypesView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TerminalTypesView")
        TerminalTypesView terminalTypesView);

    /**
     * 
     * @param transactionsView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.TransactionsViewResponse
     */
    @WebMethod(operationName = "TransactionsView")
    @WebResult(name = "TransactionsViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TransactionsViewResponse")
    public TransactionsViewResponse transactionsView(
        @WebParam(name = "TransactionsView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TransactionsView")
        TransactionsView transactionsView);

    /**
     * 
     * @param transactionsQueue
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.TransactionsQueueResponse
     */
    @WebMethod(operationName = "TransactionsQueue")
    @WebResult(name = "TransactionsQueueResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TransactionsQueueResponse")
    public TransactionsQueueResponse transactionsQueue(
        @WebParam(name = "TransactionsQueue", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "TransactionsQueue")
        TransactionsQueue transactionsQueue);

    /**
     * 
     * @param valueTypeAdd
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ValueTypeAddResponse
     */
    @WebMethod(operationName = "ValueTypeAdd")
    @WebResult(name = "ValueTypeAddResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ValueTypeAddResponse")
    public ValueTypeAddResponse valueTypeAdd(
        @WebParam(name = "ValueTypeAdd", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ValueTypeAdd")
        ValueTypeAdd valueTypeAdd);

    /**
     * 
     * @param valueTypeEdit
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ValueTypeEditResponse
     */
    @WebMethod(operationName = "ValueTypeEdit")
    @WebResult(name = "ValueTypeEditResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ValueTypeEditResponse")
    public ValueTypeEditResponse valueTypeEdit(
        @WebParam(name = "ValueTypeEdit", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ValueTypeEdit")
        ValueTypeEdit valueTypeEdit);

    /**
     * 
     * @param valueTypesView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.ValueTypesViewResponse
     */
    @WebMethod(operationName = "ValueTypesView")
    @WebResult(name = "ValueTypesViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ValueTypesViewResponse")
    public ValueTypesViewResponse valueTypesView(
        @WebParam(name = "ValueTypesView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "ValueTypesView")
        ValueTypesView valueTypesView);

    /**
     * 
     * @param walletOffersView
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseAdminWsdl.WalletOffersViewResponse
     */
    @WebMethod(operationName = "WalletOffersView")
    @WebResult(name = "WalletOffersViewResponse", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "WalletOffersViewResponse")
    public WalletOffersViewResponse walletOffersView(
        @WebParam(name = "WalletOffersView", targetNamespace = "urn:SparkbaseAdminV45Wsdl", partName = "WalletOffersView")
        WalletOffersView walletOffersView);

}
