
package org.mq.marketer.sparkbase.sparkbaseTransactionWsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SparkbaseTransactionWsdlPort", targetNamespace = "urn:SparkbaseTransactionWsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SparkbaseTransactionWsdlPort {


    /**
     * 
     * @param accountHistory
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.AccountHistoryResponse
     */
    @WebMethod(operationName = "AccountHistory")
    @WebResult(name = "AccountHistoryResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "AccountHistoryResponse")
    public AccountHistoryResponse accountHistory(
        @WebParam(name = "AccountHistory", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "AccountHistory")
        AccountHistory accountHistory);

    /**
     * 
     * @param deactivate
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.DeactivateResponse
     */
    @WebMethod(operationName = "Deactivate")
    @WebResult(name = "DeactivateResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "DeactivateResponse")
    public DeactivateResponse deactivate(
        @WebParam(name = "Deactivate", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "Deactivate")
        Deactivate deactivate);

    /**
     * 
     * @param employeeReport
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.EmployeeReportResponse
     */
    @WebMethod(operationName = "EmployeeReport")
    @WebResult(name = "EmployeeReportResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "EmployeeReportResponse")
    public EmployeeReportResponse employeeReport(
        @WebParam(name = "EmployeeReport", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "EmployeeReport")
        EmployeeReport employeeReport);

    /**
     * 
     * @param enrollment
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.EnrollmentResponse
     */
    @WebMethod(operationName = "Enrollment")
    @WebResult(name = "EnrollmentResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "EnrollmentResponse")
    public EnrollmentResponse enrollment(
        @WebParam(name = "Enrollment", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "Enrollment")
        Enrollment enrollment);

    /**
     * 
     * @param giftIssuance
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.GiftIssuanceResponse
     */
    @WebMethod(operationName = "GiftIssuance")
    @WebResult(name = "GiftIssuanceResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "GiftIssuanceResponse")
    public GiftIssuanceResponse giftIssuance(
        @WebParam(name = "GiftIssuance", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "GiftIssuance")
        GiftIssuance giftIssuance);

    /**
     * 
     * @param giftRedemption
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.GiftRedemptionResponse
     */
    @WebMethod(operationName = "GiftRedemption")
    @WebResult(name = "GiftRedemptionResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "GiftRedemptionResponse")
    public GiftRedemptionResponse giftRedemption(
        @WebParam(name = "GiftRedemption", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "GiftRedemption")
        GiftRedemption giftRedemption);

    /**
     * 
     * @param hold
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.HoldResponse
     */
    @WebMethod(operationName = "Hold")
    @WebResult(name = "HoldResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "HoldResponse")
    public HoldResponse hold(
        @WebParam(name = "Hold", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "Hold")
        Hold hold);

    /**
     * 
     * @param holdRedemption
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.HoldRedemptionResponse
     */
    @WebMethod(operationName = "HoldRedemption")
    @WebResult(name = "HoldRedemptionResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "HoldRedemptionResponse")
    public HoldRedemptionResponse holdRedemption(
        @WebParam(name = "HoldRedemption", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "HoldRedemption")
        HoldRedemption holdRedemption);

    /**
     * 
     * @param holdReturn
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.HoldReturnResponse
     */
    @WebMethod(operationName = "HoldReturn")
    @WebResult(name = "HoldReturnResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "HoldReturnResponse")
    public HoldReturnResponse holdReturn(
        @WebParam(name = "HoldReturn", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "HoldReturn")
        HoldReturn holdReturn);

    /**
     * 
     * @param inquiry
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.InquiryResponse
     */
    @WebMethod(operationName = "Inquiry")
    @WebResult(name = "InquiryResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "InquiryResponse")
    public InquiryResponse inquiry(
        @WebParam(name = "Inquiry", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "Inquiry")
        Inquiry inquiry);

    /**
     * 
     * @param loyaltyIssuance
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.LoyaltyIssuanceResponse
     */
    @WebMethod(operationName = "LoyaltyIssuance")
    @WebResult(name = "LoyaltyIssuanceResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "LoyaltyIssuanceResponse")
    public LoyaltyIssuanceResponse loyaltyIssuance(
        @WebParam(name = "LoyaltyIssuance", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "LoyaltyIssuance")
        LoyaltyIssuance loyaltyIssuance);

    /**
     * 
     * @param loyaltyRedemption
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.LoyaltyRedemptionResponse
     */
    @WebMethod(operationName = "LoyaltyRedemption")
    @WebResult(name = "LoyaltyRedemptionResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "LoyaltyRedemptionResponse")
    public LoyaltyRedemptionResponse loyaltyRedemption(
        @WebParam(name = "LoyaltyRedemption", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "LoyaltyRedemption")
        LoyaltyRedemption loyaltyRedemption);

    /**
     * 
     * @param merchandiseReturn
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.MerchandiseReturnResponse
     */
    @WebMethod(operationName = "MerchandiseReturn")
    @WebResult(name = "MerchandiseReturnResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "MerchandiseReturnResponse")
    public MerchandiseReturnResponse merchandiseReturn(
        @WebParam(name = "MerchandiseReturn", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "MerchandiseReturn")
        MerchandiseReturn merchandiseReturn);

    /**
     * 
     * @param multipleIssuance
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.MultipleIssuanceResponse
     */
    @WebMethod(operationName = "MultipleIssuance")
    @WebResult(name = "MultipleIssuanceResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "MultipleIssuanceResponse")
    public MultipleIssuanceResponse multipleIssuance(
        @WebParam(name = "MultipleIssuance", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "MultipleIssuance")
        MultipleIssuance multipleIssuance);

    /**
     * 
     * @param promotionIssuance
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.PromotionIssuanceResponse
     */
    @WebMethod(operationName = "PromotionIssuance")
    @WebResult(name = "PromotionIssuanceResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "PromotionIssuanceResponse")
    public PromotionIssuanceResponse promotionIssuance(
        @WebParam(name = "PromotionIssuance", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "PromotionIssuance")
        PromotionIssuance promotionIssuance);

    /**
     * 
     * @param promotionRedemption
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.PromotionRedemptionResponse
     */
    @WebMethod(operationName = "PromotionRedemption")
    @WebResult(name = "PromotionRedemptionResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "PromotionRedemptionResponse")
    public PromotionRedemptionResponse promotionRedemption(
        @WebParam(name = "PromotionRedemption", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "PromotionRedemption")
        PromotionRedemption promotionRedemption);

    /**
     * 
     * @param quickTransaction
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.QuickTransactionResponse
     */
    @WebMethod(operationName = "QuickTransaction")
    @WebResult(name = "QuickTransactionResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "QuickTransactionResponse")
    public QuickTransactionResponse quickTransaction(
        @WebParam(name = "QuickTransaction", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "QuickTransaction")
        QuickTransaction quickTransaction);

    /**
     * 
     * @param renew
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.RenewResponse
     */
    @WebMethod(operationName = "Renew")
    @WebResult(name = "RenewResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "RenewResponse")
    public RenewResponse renew(
        @WebParam(name = "Renew", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "Renew")
        Renew renew);

    /**
     * 
     * @param terminalReport
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.TerminalReportResponse
     */
    @WebMethod(operationName = "TerminalReport")
    @WebResult(name = "TerminalReportResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "TerminalReportResponse")
    public TerminalReportResponse terminalReport(
        @WebParam(name = "TerminalReport", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "TerminalReport")
        TerminalReport terminalReport);

    /**
     * 
     * @param tip
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.TipResponse
     */
    @WebMethod(operationName = "Tip")
    @WebResult(name = "TipResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "TipResponse")
    public TipResponse tip(
        @WebParam(name = "Tip", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "Tip")
        Tip tip);

    /**
     * 
     * @param transfer
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.TransferResponse
     */
    @WebMethod(operationName = "Transfer")
    @WebResult(name = "TransferResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "TransferResponse")
    public TransferResponse transfer(
        @WebParam(name = "Transfer", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "Transfer")
        Transfer transfer);

    /**
     * 
     * @param voidTransaction
     * @return
     *     returns org.mq.marketer.sparkbase.sparkbaseTransactionWsdl.VoidTransactionResponse
     */
    @WebMethod(operationName = "VoidTransaction")
    @WebResult(name = "VoidTransactionResponse", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "VoidTransactionResponse")
    public VoidTransactionResponse voidTransaction(
        @WebParam(name = "VoidTransaction", targetNamespace = "urn:SparkbaseTransactionWsdl", partName = "VoidTransaction")
        VoidTransaction voidTransaction);

}
