package org.mq.marketer.campaign.beans;
// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;

/**
 * AuditTrails generated by hbm2java
 */
@SuppressWarnings("serial")
public class AuditTrails  implements java.io.Serializable {


     /**
	 * 
	 */
	private Long id;
    private String IP;
    private String status;
    private Calendar date;
    private Users users;

    public AuditTrails() {
    }

    public AuditTrails(String IP, String status, Calendar date, Users users) {
       this.IP = IP;
       this.status = status;
       this.date = date;
       this.users = users;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getIP() {
        return this.IP;
    }
    
    public void setIP(String IP) {
        this.IP = IP;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Calendar getDate() {
        return this.date;
    }
    
    public void setDate(Calendar date) {
        this.date = date;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


