package org.mq.marketer.campaign.beans;
// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1



/**
 * CampaignSegmentFields generated by hbm2java
 */
public class CampaignSegmentFields  implements java.io.Serializable {


     private Long id;
     private Campaigns campaignId;
     private String condition;
     private String paramOne;
     private String paramTwo;

    public CampaignSegmentFields() {
    }

	
    public CampaignSegmentFields(Campaigns campaignId) {
        this.campaignId = campaignId;
    }
    public CampaignSegmentFields(Campaigns campaignId, String condition, String paramOne, String paramTwo) {
       this.campaignId = campaignId;
       this.condition = condition;
       this.paramOne = paramOne;
       this.paramTwo = paramTwo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Campaigns getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(Campaigns campaignId) {
        this.campaignId = campaignId;
    }
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }
    public String getParamOne() {
        return this.paramOne;
    }
    
    public void setParamOne(String paramOne) {
        this.paramOne = paramOne;
    }
    public String getParamTwo() {
        return this.paramTwo;
    }
    
    public void setParamTwo(String paramTwo) {
        this.paramTwo = paramTwo;
    }

}


