package org.mq.marketer.campaign.beans;
// Generated 26 Jun, 2009 6:00:45 PM by Hibernate Tools 3.2.0.CR1

/**
 * CustomFieldData generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class CustomFieldData  implements java.io.Serializable {


     private Long cId;
     private Contacts contact;
     private String cust1;
     private String cust2;
     private String cust3;
     private String cust4;
     private String cust5;
     private String cust6;
     private String cust7;
     private String cust8;
     private String cust9;
     private String cust10;
     private String cust11;
     private String cust12;
     private String cust13;
     private String cust14;
     private String cust15;
     private String cust16;
     private String cust17;
     private String cust18;
     private String cust19;
     private String cust20;

    public CustomFieldData() {
    }

	
    public CustomFieldData(Contacts emailId) {
        this.contact = emailId;
    }
    public CustomFieldData(Contacts contact, String cust1, String cust2, String cust3, String cust4, String cust5, String cust6, String cust7, String cust8, String cust9, String cust10, String cust11, String cust12, String cust13, String cust14, String cust15, String cust16, String cust17, String cust18, String cust19, String cust20) {
       this.contact = contact;
       this.cust1 = cust1;
       this.cust2 = cust2;
       this.cust3 = cust3;
       this.cust4 = cust4;
       this.cust5 = cust5;
       this.cust6 = cust6;
       this.cust7 = cust7;
       this.cust8 = cust8;
       this.cust9 = cust9;
       this.cust10 = cust10;
       this.cust11 = cust11;
       this.cust12 = cust12;
       this.cust13 = cust13;
       this.cust14 = cust14;
       this.cust15 = cust15;
       this.cust16 = cust16;
       this.cust17 = cust17;
       this.cust18 = cust18;
       this.cust19 = cust19;
       this.cust20 = cust20;
    }
   
    public Long getcId() {
        return this.cId;
    }
    
    public void setcId(Long cId) {
        this.cId = cId;
    }
    public Contacts getContact() {
        return this.contact;
    }
    
    public void setContact(Contacts contact) {
        this.contact = contact;
    }
    public String getCust1() {
        return this.cust1;
    }
    
    public void setCust1(String cust1) {
        this.cust1 = cust1;
    }
    public String getCust2() {
        return this.cust2;
    }
    
    public void setCust2(String cust2) {
        this.cust2 = cust2;
    }
    public String getCust3() {
        return this.cust3;
    }
    
    public void setCust3(String cust3) {
        this.cust3 = cust3;
    }
    public String getCust4() {
        return this.cust4;
    }
    
    public void setCust4(String cust4) {
        this.cust4 = cust4;
    }
    public String getCust5() {
        return this.cust5;
    }
    
    public void setCust5(String cust5) {
        this.cust5 = cust5;
    }
    public String getCust6() {
        return this.cust6;
    }
    
    public void setCust6(String cust6) {
        this.cust6 = cust6;
    }
    public String getCust7() {
        return this.cust7;
    }
    
    public void setCust7(String cust7) {
        this.cust7 = cust7;
    }
    public String getCust8() {
        return this.cust8;
    }
    
    public void setCust8(String cust8) {
        this.cust8 = cust8;
    }
    public String getCust9() {
        return this.cust9;
    }
    
    public void setCust9(String cust9) {
        this.cust9 = cust9;
    }
    public String getCust10() {
        return this.cust10;
    }
    
    public void setCust10(String cust10) {
        this.cust10 = cust10;
    }
    public String getCust11() {
        return this.cust11;
    }
    
    public void setCust11(String cust11) {
        this.cust11 = cust11;
    }
    public String getCust12() {
        return this.cust12;
    }
    
    public void setCust12(String cust12) {
        this.cust12 = cust12;
    }
    public String getCust13() {
        return this.cust13;
    }
    
    public void setCust13(String cust13) {
        this.cust13 = cust13;
    }
    public String getCust14() {
        return this.cust14;
    }
    
    public void setCust14(String cust14) {
        this.cust14 = cust14;
    }
    public String getCust15() {
        return this.cust15;
    }
    
    public void setCust15(String cust15) {
        this.cust15 = cust15;
    }
    public String getCust16() {
        return this.cust16;
    }
    
    public void setCust16(String cust16) {
        this.cust16 = cust16;
    }
    public String getCust17() {
        return this.cust17;
    }
    
    public void setCust17(String cust17) {
        this.cust17 = cust17;
    }
    public String getCust18() {
        return this.cust18;
    }
    
    public void setCust18(String cust18) {
        this.cust18 = cust18;
    }
    public String getCust19() {
        return this.cust19;
    }
    
    public void setCust19(String cust19) {
        this.cust19 = cust19;
    }
    public String getCust20() {
        return this.cust20;
    }
    
    public void setCust20(String cust20) {
        this.cust20 = cust20;
    }
    
    @Override
    public String toString() {
    	String cfData = cust1 + " , " + cust2 + " , " + cust3 + " , " + cust4 + " , " + cust5 + " , " + 
    					cust6 + " , " + cust7 + " , " + cust8 + " , " + cust9 + " , " + cust10 + " , " + 
    					cust11 + " , " + cust12 + " , " + cust13 + " , " + cust14 + " , " + cust15 + " , " 
    					+ cust16 + " , " + cust17 + " , " + cust18 + " , " + cust19 + " , " + cust20;
    	return cfData;
    }
}

