package org.mq.marketer.campaign.beans;
// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;

/**
 * MyTemplates generated by hbm2java
 */

public class MyTemplates  implements java.io.Serializable {


	private Long myTemplateId;
	private String name;
	private String content;
	private String jsoncontent;
	private Calendar createdDate;
	private String editorType;
	private Users users;

	private String folderName;
	private String parentDir;   
	public String getParentDir() {
		return parentDir;	
	}
	public void setParentDir(String parentDir) {		
		this.parentDir = parentDir;
	}

	public String getFolderName() {
		return folderName;
	}


	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	 private Calendar modifiedDate;

	    public Calendar getModifiedDate() {
	        return modifiedDate;
	    }


	    public void setModifiedDate(Calendar modifiedDate) {
	        this.modifiedDate = modifiedDate;
	    }

	public MyTemplates() {
    }

	
    public MyTemplates(String name, String editorType) {
        this.name = name;
        this.editorType = editorType;
    }
    public MyTemplates(String name, String content, Calendar createdDate, String editorType, Users users) {
       this.name = name;
       this.content = content;
       this.createdDate = createdDate;
       this.editorType = editorType;
       this.users = users;
    }
    public MyTemplates(String name, String content, Calendar createdDate, String editorType, Users users,String folderName,String parentDir) {
        this.name = name;
        this.content = content;
        this.createdDate = createdDate;
        this.editorType = editorType;
        this.users = users;
        this.folderName= folderName;
        this.parentDir = parentDir;
     }
    public MyTemplates(String name, String content, Calendar createdDate, String editorType, Users users,String folderName, String jsoncontent, String parentDir ) {
		this.name = name;
		this.content = content;
		this.createdDate = createdDate;
		this.editorType = editorType;
		this.users = users;
		this.folderName = folderName;
		this.jsoncontent = jsoncontent; 
		this.parentDir = parentDir;
	}
   
    public Long getMyTemplateId() {
        return this.myTemplateId;
    }
    
    public void setMyTemplateId(Long myTemplateId) {
        this.myTemplateId = myTemplateId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getJsoncontent() {
		return jsoncontent;
	}
	public void setJsoncontent(String jsoncontent) {
		this.jsoncontent = jsoncontent;
	}
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    public String getEditorType() {
        return this.editorType;
    }
    
    public void setEditorType(String editorType) {
        this.editorType = editorType;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

}


