package org.mq.marketer.campaign.beans;
// Generated 25 Jul, 2009 12:12:10 PM by Hibernate Tools 3.2.0.CR1



/**
 * SubscriptionPlan generated by hbm2java
 */
@SuppressWarnings("serial")
public class SubscriptionPlan  implements java.io.Serializable {

     private Long subscriptionId;
     private String planName;
     private Long contactsLimit;
     private Long contactsperListLimit;
     private int mailingListsLimit;
     private int galleryListLimit;
     private int galleryMemoryLimit;
     private int campaignsLimit;
     private Long emailsLimit;
     private UserRoles userRoles;

    public SubscriptionPlan() {
    }

    public SubscriptionPlan(String planName, Long contactsLimit, Long contactsperListLimit, int mailingListsLimit, int galleryListLimit, int galleryMemoryLimit, int campaignsLimit, Long emailsLimit, UserRoles userRoles) {
       this.planName = planName;
       this.contactsLimit = contactsLimit;
       this.contactsperListLimit = contactsperListLimit;
       this.mailingListsLimit = mailingListsLimit;
       this.galleryListLimit = galleryListLimit;
       this.galleryMemoryLimit = galleryMemoryLimit;
       this.campaignsLimit = campaignsLimit;
       this.emailsLimit = emailsLimit;
       this.userRoles = userRoles;
    }
   
    public Long getSubscriptionId() {
        return this.subscriptionId;
    }
    
    public void setSubscriptionId(Long subscriptionId) {
        this.subscriptionId = subscriptionId;
    }
    public String getPlanName() {
        return this.planName;
    }
    
    public void setPlanName(String planName) {
        this.planName = planName;
    }
    public Long getContactsLimit() {
        return this.contactsLimit;
    }
    
    public void setContactsLimit(Long contactsLimit) {
        this.contactsLimit = contactsLimit;
    }
    public Long getContactsperListLimit() {
        return this.contactsperListLimit;
    }
    
    public void setContactsperListLimit(Long contactsperListLimit) {
        this.contactsperListLimit = contactsperListLimit;
    }
    public int getMailingListsLimit() {
        return this.mailingListsLimit;
    }
    
    public void setMailingListsLimit(int mailingListsLimit) {
        this.mailingListsLimit = mailingListsLimit;
    }
    public int getGalleryListLimit() {
        return this.galleryListLimit;
    }
    
    public void setGalleryListLimit(int galleryListLimit) {
        this.galleryListLimit = galleryListLimit;
    }
    public int getGalleryMemoryLimit() {
        return this.galleryMemoryLimit;
    }
    
    public void setGalleryMemoryLimit(int galleryMemoryLimit) {
        this.galleryMemoryLimit = galleryMemoryLimit;
    }
    public int getCampaignsLimit() {
        return this.campaignsLimit;
    }
    
    public void setCampaignsLimit(int campaignsLimit) {
        this.campaignsLimit = campaignsLimit;
    }
    public Long getEmailsLimit() {
        return this.emailsLimit;
    }
    
    public void setEmailsLimit(Long emailsLimit) {
        this.emailsLimit = emailsLimit;
    }
    public UserRoles getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(UserRoles userRoles) {
        this.userRoles = userRoles;
    }

}

