package org.mq.marketer.campaign.beans;

import java.util.Calendar;

// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1



/**
 * Unsubscribes generated by hbm2java
 */
public class Unsubscribes  implements java.io.Serializable {


     private Long unsubscribeId;
     private String emailId;
     private String reason;
     private Calendar date;
    // private Users users;

     private short unsubcategoriesWeight;
     private Long userId;
    public Long getUserId() {
		return userId;
	}


	public void setUserId(Long userId) {
		this.userId = userId;
	}


	public Unsubscribes() {
    }

	
    public Unsubscribes(String emailId) {
        this.emailId = emailId;
    }
    public Unsubscribes(String emailId, String reason, Calendar date, Long userId) {
       this.emailId = emailId;
       this.reason = reason;
       this.date = date;
       this.userId = userId;
    }
   
    public Long getUnsubscribeId() {
        return this.unsubscribeId;
    }
    
    public void setUnsubscribeId(Long unsubscribeId) {
        this.unsubscribeId = unsubscribeId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Calendar getDate() {
        return this.date;
    }
    
    public void setDate(Calendar date) {
        this.date = date;
    }
    
    
    public short getUnsubcategoriesWeight() {
		return unsubcategoriesWeight;
	}

	public void setUnsubcategoriesWeight(short unsubcategoriesWeight) {
		this.unsubcategoriesWeight = unsubcategoriesWeight;
	}
}





/*import java.util.Date;

// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1



*//**
 * Unsubscribes generated by hbm2java
 *//*
public class Unsubscribes  implements java.io.Serializable {

	  private Long unsubscribeId;
	     private String reason;
	     private Date unsubscribedDate;
	     private String emailId;
	     private short unsubcategoriesWeight;
	     private Long userId;

	    public Unsubscribes() {
	    }

	    public Long getUnsubscribeId() {
	        return this.unsubscribeId;
	    }
	    
	    public void setUnsubscribeId(Long unsubscribeId) {
	        this.unsubscribeId = unsubscribeId;
	    }

	    public String getReason() {
	        return this.reason;
	    }
	    
	    public void setReason(String reason) {
	        this.reason = reason;
	    }
	    public Date getUnsubscribedDate() {
	        return this.unsubscribedDate;
	    }
	    
	    public void setUnsubscribedDate(Date unsubscribedDate) {
	        this.unsubscribedDate = unsubscribedDate;
	    }
	    
	    public Long getuserId() {
	        return this.userId;
	    }
	    
	    public void setUserId(Long userId) {
	        this.userId = userId;
	    }

		public String getEmailId() {
			return emailId;
		}

		public void setEmailId(String emailId) {
			this.emailId = emailId;
		}

		public short getUnsubcategoriesWeight() {
			return unsubcategoriesWeight;
		}

		public void setUnsubcategoriesWeight(short unsubcategoriesWeight) {
			this.unsubcategoriesWeight = unsubcategoriesWeight;
		}

		
}
*/



