package org.mq.marketer.campaign.beans;

import java.util.Calendar;

// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1



/**
 * UserActivities generated by hbm2java
 */
public class UserActivities  implements java.io.Serializable,Comparable {


     private Long id;
     private String activity;
     private String module;
     private Calendar date;
     private Long userId;

    public UserActivities() {
    }

    public UserActivities(String activity,String module,Calendar date, Long userId) {
       this.activity = activity;
       this.date = date;
       this.userId = userId;
       this.module = module;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }
    public Calendar getDate() {
        return this.date;
    }
    
    public void setDate(Calendar date) {
        this.date = date;
    }
  
    public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Override
	public int compareTo(Object arg0) {
		return this.id.intValue();
	}


}


