package org.mq.marketer.campaign.beans;
// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;

/**
 * CampaignSent generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class CampaignSent  implements java.io.Serializable {


     private Long sentId;
     private String emailId;
     private CampaignReport campaignReport;
     private String status;
     private int opens;
     private int clicks;
     private Calendar bounceTime;
     private String bounceInfo;
     private Long campaignId;
     private Long contactId;
     

	private String contactPhValStr;

    public CampaignSent() {
    }

	
    public CampaignSent(String emailId, CampaignReport campaignReport, String status) {
        this.emailId = emailId;
        this.campaignReport = campaignReport;
        this.status = status;
    }

	public CampaignSent(Long sentId,String emailId, int opens) {
    	this.sentId = sentId;
        this.emailId = emailId;
        this.opens = opens;
    }

    public CampaignSent(String emailId, CampaignReport campaignReport, 
    		String status, int opens, int clicks, Calendar bounceTime, String bounceInfo) {
    	
       this.emailId = emailId;
       this.campaignReport = campaignReport;
       this.status = status;
       this.opens = opens;
       this.clicks = clicks;
       this.bounceTime = bounceTime;
       this.bounceInfo = bounceInfo;
    }
   
    public Long getSentId() {
        return this.sentId;
    }
    
    public void setSentId(Long sentId) {
        this.sentId = sentId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public CampaignReport getCampaignReport() {
        return this.campaignReport;
    }
    
    public void setCampaignReport(CampaignReport campaignReport) {
        this.campaignReport = campaignReport;
    }

	public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public int getOpens() {
        return this.opens;
    }
    
    public void setOpens(int opens) {
        this.opens = opens;
    }
    public int getClicks() {
        return this.clicks;
    }
    
    public void setClicks(int clicks) {
        this.clicks = clicks;
    }
    public Calendar getBounceTime() {
        return this.bounceTime;
    }
    
    public void setBounceTime(Calendar bounceTime) {
        this.bounceTime = bounceTime;
    }
    public String getBounceInfo() {
        return this.bounceInfo;
    }
    
    public void setBounceInfo(String bounceInfo) {
        this.bounceInfo = bounceInfo;
    }


    public Long getContactId() {
		return contactId;
	}


	public void setContactId(Long contactId) {
		this.contactId = contactId;
	}
    
	public Long getCampaignId() {
		return campaignId;
	}


	public void setCampaignId(Long campaignId) {
		this.campaignId = campaignId;
	}

	public String getContactPhValStr() {
		return contactPhValStr;
	}


	public void setContactPhValStr(String contactPhValStr) {
		this.contactPhValStr = contactPhValStr;
	}

}


