package org.mq.marketer.campaign.beans;
// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;

/**
 * Clicks generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class Clicks  implements java.io.Serializable {


     private Long clickId;
     private Long crId;
     private Long sentId;
     private String clickUrl;
     private Calendar clickDate;
     private String userAgent;

    public Clicks() {
    }

	
    public Clicks(Long sentId) {
        this.sentId = sentId;
    }
    public Clicks(Long sentId, String clickUrl, Calendar clickDate, String userAgent) {
       this.sentId = sentId;
       this.clickUrl = clickUrl;
       this.clickDate = clickDate;
       this.userAgent = userAgent;
    }
   
    public Long getClickId() {
        return this.clickId;
    }
    
    public void setClickId(Long clickId) {
        this.clickId = clickId;
    }
    
    
    public Long getCrId() {
		return crId;
	}


	public void setCrId(Long crId) {
		this.crId = crId;
	}


	public Long getSentId() {
        return this.sentId;
    }
    
    public void setSentId(Long sentId) {
        this.sentId = sentId;
    }
    public String getClickUrl() {
        return this.clickUrl;
    }
    
    public void setClickUrl(String clickUrl) {
        this.clickUrl = clickUrl;
    }
    public Calendar getClickDate() {
        return this.clickDate;
    }
    
    public void setClickDate(Calendar clickDate) {
        this.clickDate = clickDate;
    }


	public String getUserAgent() {
		return userAgent;
	}


	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}




}


