package org.mq.marketer.campaign.beans;
// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1



/**
 * EmailClient generated by hbm2java
 */
public class EmailClient  implements java.io.Serializable {


    private Long emailClientId;
    private String emailClient;
    private String userAgent;
    
    private String uaDispValue;
    private String userAgentStr;

    
    public EmailClient() {
    	
    }

   public EmailClient(String emailClient,String userAgent) {
	   this.emailClient = emailClient;
	   this.userAgent = userAgent;
   }

   
   
   public EmailClient(String emailClient, String userAgent, String uaDispValue,
		String userAgentStr) {
	super();
	this.emailClient = emailClient;
	this.userAgent = userAgent;
	this.uaDispValue = uaDispValue;
	this.userAgentStr = userAgentStr;
}

public EmailClient(String emailClient) {
      this.emailClient = emailClient;
   }
  
   public Long getEmailClientId() {
       return this.emailClientId;
   }
   
   public void setEmailClientId(Long emailClientId) {
       this.emailClientId = emailClientId;
   }
   public String getEmailClient() {
       return this.emailClient;
   }
   
   public void setEmailClient(String emailClient) {
       this.emailClient = emailClient;
   }

	public String getUserAgent() {
		return userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	public String getUaDispValue() {
		return uaDispValue;
	}

	public void setUaDispValue(String uaDispValue) {
		this.uaDispValue = uaDispValue;
	}

	public String getUserAgentStr() {
		return userAgentStr;
	}

	public void setUserAgentStr(String userAgentStr) {
		this.userAgentStr = userAgentStr;
	}
	
	
}



