package org.mq.marketer.campaign.beans;
// Generated 14 May, 2009 12:22:57 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/**
 * EmailLayout generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class EmailLayout  implements java.io.Serializable {


     private Long emailLayoutId;
     private String layoutName;
     private Calendar createdDate;
     private String status;
     private Calendar lastModifiedDate;
     private String htmlText;
     private String finalHtmlText;
     private boolean prepared;
     private String editorType;
     private Users users;
     private SystemTemplates template;
     @SuppressWarnings("unchecked")
	private Set campaigns = new HashSet(0);

    public EmailLayout() {
    }

	
    public EmailLayout(String layoutName, String editorType, Users users, SystemTemplates template) {
        this.layoutName = layoutName;
        this.editorType = editorType;
        this.users = users;
        this.template = template;
    }
    public EmailLayout(String layoutName, Calendar createdDate, String status, Calendar lastModifiedDate, String htmlText, String editorType, Users users, SystemTemplates template, Set campaigns) {
       this.layoutName = layoutName;
       this.createdDate = createdDate;
       this.status = status;
       this.lastModifiedDate = lastModifiedDate;
       this.htmlText = htmlText;
       this.editorType = editorType;
       this.users = users;
       this.template = template;
       this.campaigns = campaigns;
    }
    public EmailLayout(String layoutName, Calendar createdDate, String status, Calendar lastModifiedDate, String htmlText, String editorType, Users users, SystemTemplates template) {
        this.layoutName = layoutName;
        this.createdDate = createdDate;
        this.status = status;
        this.lastModifiedDate = lastModifiedDate;
        this.htmlText = htmlText;
        this.editorType = editorType;
        this.users = users;
        this.template = template;
     }
    
   
    public Long getEmailLayoutId() {
        return this.emailLayoutId;
    }
    
    public void setEmailLayoutId(Long emailLayoutId) {
        this.emailLayoutId = emailLayoutId;
    }
    public String getLayoutName() {
        return this.layoutName;
    }
    
    public void setLayoutName(String layoutName) {
        this.layoutName = layoutName;
    }
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Calendar getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Calendar lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public String getHtmlText() {
        return this.htmlText;
    }
    
    public void setHtmlText(String htmlText) {
        this.htmlText = htmlText;
    }
    public String getEditorType() {
        return this.editorType;
    }
    
    public void setEditorType(String editorType) {
        this.editorType = editorType;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public SystemTemplates getTemplate() {
        return this.template;
    }
    
    public void setTemplate(SystemTemplates template) {
        this.template = template;
    }
    public Set getCampaigns() {
        return this.campaigns;
    }
    
    public void setCampaigns(Set campaigns) {
        this.campaigns = campaigns;
    }


	public String getFinalHtmlText() {
		return finalHtmlText;
	}


	public void setFinalHtmlText(String finalHtmlText) {
		this.finalHtmlText = finalHtmlText;
	}


	public boolean isPrepared() {
		return prepared;
	}


	public void setPrepared(boolean prepared) {
		this.prepared = prepared;
	}







}


