package org.mq.marketer.campaign.beans;
// Generated Nov 25, 2008 11:19:15 AM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import org.mq.marketer.campaign.beans.EventTrigger;

/**
 * MailingList generated by hbm2java
 */
@SuppressWarnings({ "unchecked", "serial" })
public class MailingList  implements java.io.Serializable {

	 private Long listId;
     private String listName;
     private String description;
     private Calendar createdDate;
     private String status;
     private Calendar lastStatusChangeDate;
     private Calendar lastModifiedDate;
     private boolean custField;
     private boolean consent;
     private Set<Campaigns> campaigns = new HashSet(0);
     private Set<SMSCampaigns> smsCampaigns = new HashSet(0); 
     private Set<AutoProgram> autoPrograms = new HashSet(0);
     private Set<UsersDomains> sharedToDomain = new HashSet(0);//added for sharing
    
    

	private Users users;
     private Long size;
     private Long unPergedCount;
     private Long custTemplateId;
     private boolean checkDoubleOptin;
     private boolean checkParentalConsent;
     private Long consentCutomTempId;
     
     //added after auto email
     private boolean checkLoyaltyOptin;
     private Long loyaltyCutomTempId;

	//added after webform welcome email
     private boolean checkWelcomeMsg;
     private Long welcomeCustTempId;
  // added for performance
 	private Long listSize;
     public Long getWelcomeCustTempId() {
    	 return welcomeCustTempId;
     }
     
     public void setWelcomeCustTempId(Long welcomeCustTempId) {
    	 this.welcomeCustTempId = welcomeCustTempId;
     }
     
     public boolean isCheckWelcomeMsg() {
		return checkWelcomeMsg;
	}

	public void setCheckWelcomeMsg(boolean checkWelcomeMsg) {
		this.checkWelcomeMsg = checkWelcomeMsg;
	}

     
     public Long getConsentCutomTempId() {
		return consentCutomTempId;
	}

	public void setConsentCutomTempId(Long consentCutomTempId) {
		this.consentCutomTempId = consentCutomTempId;
	}

	public boolean isCheckParentalConsent() {
		return checkParentalConsent;
	}

	public void setCheckParentalConsent(boolean checkParentalConsent) {
		this.checkParentalConsent = checkParentalConsent;
	}

	private Set<EventTrigger> triggersSet = new HashSet(0);
     
     private String listType;//added for POS 
//     private Set<EventTrigger> triggerSetToBeCopiedToMls = new HashSet(0);
     private Long mlBit;
	
	public MailingList() {
    }
	
    public MailingList(MailingList mlist){
        this.listName = mlist.getListName();
        this.description = mlist.getDescription();
        this.createdDate = Calendar.getInstance();
        this.status = mlist.getStatus();
        this.users = mlist.getUsers();
    }
	
    public Set<EventTrigger> getTriggersSet() {
		return triggersSet;
	}
	public void setTriggersSet(Set<EventTrigger> triggersSet) {
		this.triggersSet = triggersSet;
	}
	
    public MailingList(String listName, boolean consent,Users users) {
        this.listName = listName;
        this.users = users;
        this.consent = consent;
    }
    
    public MailingList(Long listId, String listName, Long size) {
        this.listName = listName;
        this.listId = listId;
        this.size = size;
    }

    public MailingList(Long listId, String listName, Long size,boolean custField) {
        this.listName = listName;
        this.listId = listId;
        this.size = size;
        this.custField =  custField;
    }
    
    public MailingList(Long listId, String listName, Long size,Long unPergedCount, String description, 
    		Calendar createdDate, Calendar lastStatusChangeDate, boolean checkDoubleOptin, boolean consent,
    		boolean custField, Calendar lastModifiedDate,Users users, String listType, Long custTemplateId) {
    	
        this.listName = listName;
        this.listId = listId;
        this.size = size;
        this.unPergedCount = unPergedCount;
        this.description = description;
        this.custField =  custField;
        this.lastModifiedDate = lastModifiedDate;
        this.users = users;
        this.createdDate = createdDate;
        this.lastStatusChangeDate = lastStatusChangeDate;
        this.checkDoubleOptin = checkDoubleOptin;
        this.consent = consent;
        this.listType = listType;
        this.custTemplateId = custTemplateId;
    }
    
    
    
    public MailingList(Long listId, String listName, Long size,Long unPergedCount, String description, 
    		Calendar createdDate, Calendar lastStatusChangeDate, boolean checkDoubleOptin, boolean consent,
    		boolean custField, Calendar lastModifiedDate,Users users, String listType, Long custTemplateId,
    		boolean checkParentalConsent, Long consentCutomTempId, Long mlBit) {
    	
        this.listName = listName;
        this.listId = listId;
        this.size = size;
        this.unPergedCount = unPergedCount;
        this.description = description;
        this.custField =  custField;
        this.lastModifiedDate = lastModifiedDate;
        this.users = users;
        this.createdDate = createdDate;
        this.lastStatusChangeDate = lastStatusChangeDate;
        this.checkDoubleOptin = checkDoubleOptin;
        this.consent = consent;
        this.listType = listType;
        this.custTemplateId = custTemplateId;
        this.checkParentalConsent = checkParentalConsent;
        this.consentCutomTempId = consentCutomTempId;
        this.mlBit = mlBit;
    }
    
    public MailingList(Long listId, String listName, Long size, String description, 
    		Calendar createdDate, Calendar lastStatusChangeDate, boolean checkDoubleOptin, boolean consent,
    		boolean custField, Calendar lastModifiedDate,Users users, String listType, Long custTemplateId,
    		boolean checkParentalConsent, Long consentCutomTempId, Long mlBit) {
    	
        this.listName = listName;
        this.listId = listId;
        this.size = size;
        this.description = description;
        this.custField =  custField;
        this.lastModifiedDate = lastModifiedDate;
        this.users = users;
        this.createdDate = createdDate;
        this.lastStatusChangeDate = lastStatusChangeDate;
        this.checkDoubleOptin = checkDoubleOptin;
        this.consent = consent;
        this.listType = listType;
        this.custTemplateId = custTemplateId;
        this.checkParentalConsent = checkParentalConsent;
        this.consentCutomTempId = consentCutomTempId;
        this.mlBit = mlBit;
    }
    
    public MailingList(Long listId, String listName, Long size,Long unPergedCount, String description, 
    		
    		boolean custField, Calendar lastModifiedDate,Users users) {
    	
        this.listName = listName;
        this.listId = listId;
        this.size = size;
        this.unPergedCount = unPergedCount;
        this.description = description;
        this.custField =  custField;
        this.lastModifiedDate = lastModifiedDate;
        this.users = users;
       /* this.createdDate = createdDate;
        this.lastStatusChangeDate = lastStatusChangeDate;
        this.checkDoubleOptin = checkDoubleOptin;
        this.consent = consent;*/
    }
    
    
    
    public MailingList(String listName, String description, Calendar createdDate, String status,
    		Calendar lastStatusChangeDate, Calendar lastModifiedDate,boolean consent, boolean custField, 
    		Set campaigns, Users users,boolean checkDoubleOptin,Long custTemplateId, 
    		boolean checkParentalConsent, Long consentCutomTempId) {
    	
       this.listName = listName;
       this.description = description;
       this.createdDate = createdDate;
       this.status = status;
       this.lastStatusChangeDate = lastStatusChangeDate;
       this.lastModifiedDate = lastModifiedDate;
       this.campaigns = campaigns;
       this.users = users;
       this.custField =  custField;
       this.consent = consent;
       this.checkDoubleOptin = checkDoubleOptin;
       this.custTemplateId = custTemplateId;
       this.checkParentalConsent = checkParentalConsent;
       this.consentCutomTempId = consentCutomTempId;
       
    }
    
    
    //added after Auto email
    public MailingList(String listName, String description, Calendar createdDate, String status,
    		Calendar lastStatusChangeDate, Calendar lastModifiedDate,boolean consent, boolean custField, 
    		Set campaigns, Users users,boolean checkDoubleOptin,Long custTemplateId, boolean checkParentalConsent,
    		Long consentCutomTempId, boolean checkLoyaltyOptin, Long loyaltyCutomTempId, boolean checkWelcomeMsg,Long welcomeCustTempId ) {
    	
        this.listName = listName;
        this.description = description;
        this.custField =  custField;
        this.lastModifiedDate = lastModifiedDate;
        this.users = users;
        this.createdDate = createdDate;
        this.lastStatusChangeDate = lastStatusChangeDate;
        this.checkDoubleOptin = checkDoubleOptin;
        this.consent = consent;
        this.custTemplateId = custTemplateId;
        this.checkParentalConsent = checkParentalConsent;
        this.consentCutomTempId = consentCutomTempId;
        this.loyaltyCutomTempId = loyaltyCutomTempId;
        this.checkLoyaltyOptin = checkLoyaltyOptin;
        this.checkWelcomeMsg = checkWelcomeMsg;
        this.welcomeCustTempId = welcomeCustTempId;
        this.status=status;
        this.campaigns =campaigns;
    }
    
    
    public MailingList(String listName, String description, Calendar createdDate, String status,
    		Calendar lastStatusChangeDate, Calendar lastModifiedDate,boolean consent, boolean custField, 
    		Set campaigns, Users users,boolean checkDoubleOptin, boolean checkParentalConsent) {
    	
       this(listName, description, createdDate, status, lastStatusChangeDate, lastModifiedDate, consent, custField, campaigns, users, checkDoubleOptin, null, checkParentalConsent, null);
       
    }
   
    
  //view List
    public MailingList(Long listId, String status,String listName, Long size,Long unPergedCount, String description, 
    		Calendar createdDate, Calendar lastStatusChangeDate, boolean checkDoubleOptin, boolean consent,
    		boolean custField, Calendar lastModifiedDate,Users users, String listType, Long custTemplateId,
    		boolean checkParentalConsent, Long consentCutomTempId) {
    	this.status = status;
        this.listName = listName;
        this.listId = listId;
        this.size = size;
        this.unPergedCount = unPergedCount;
        this.description = description;
        this.custField =  custField;
        this.lastModifiedDate = lastModifiedDate;
        this.users = users;
        this.createdDate = createdDate;
        this.lastStatusChangeDate = lastStatusChangeDate;
        this.checkDoubleOptin = checkDoubleOptin;
        this.consent = consent;
        this.listType = listType;
        this.custTemplateId = custTemplateId;
        this.checkParentalConsent = checkParentalConsent;
        this.consentCutomTempId = consentCutomTempId;
    }
    
    public MailingList(Long listId, String listName, String description, 
    		Calendar createdDate, Calendar lastStatusChangeDate, boolean checkDoubleOptin, boolean consent,
    		boolean custField, Calendar lastModifiedDate, Users users, String listType, Long custTemplateId,
    		boolean checkParentalConsent, Long consentCutomTempId, Long mlbit, Long listSize) {
    	
    	this.listId = listId;
    	this.listName = listName;
        this.description = description;
        this.createdDate = createdDate;
        this.lastStatusChangeDate = lastStatusChangeDate;
        this.checkDoubleOptin = checkDoubleOptin;
        this.consent = consent;
        this.custField =  custField;
        this.lastModifiedDate = lastModifiedDate;
        this.users = users;
        this.listType = listType;
        this.custTemplateId = custTemplateId;
        this.checkParentalConsent = checkParentalConsent;
        this.consentCutomTempId = consentCutomTempId;
        this.mlBit = mlbit;
        this.listSize = listSize;
    }
    
    
    
    
    public Long getListId() {
        return this.listId;
    }
    
    public void setListId(Long listId) {
        this.listId = listId;
    }
    public String getListName() {
        return this.listName;
    }
    
    public void setListName(String listName) {
        this.listName = listName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Calendar getLastStatusChangeDate() {
        return this.lastStatusChangeDate;
    }
    
    public void setLastStatusChangeDate(Calendar lastStatusChangeDate) {
        this.lastStatusChangeDate = lastStatusChangeDate;
    }
    public Calendar getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Calendar lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public boolean isCustField() {
        return this.custField;
    }
    
    public void setCustField(boolean custField) {
        this.custField = custField;
    }
	public boolean isConsent() {
		return consent;
	}
	public void setConsent(boolean consent) {
		this.consent = consent;
	}
   
	public Set<Campaigns> getCampaigns() {
        return this.campaigns;
    }
    
    public void setCampaigns(Set<Campaigns> campaigns) {
        this.campaigns = campaigns;
    }
    
    public Set<AutoProgram> getAutoPrograms() {
		return autoPrograms;
	}

	public void setAutoPrograms(Set<AutoProgram> autoPrograms) {
		this.autoPrograms = autoPrograms;
	}
    
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

	public Long getSize() {
		return size;
	}
	
	public void setSize(Long size) {
		this.size = size;
	}
	
	public Long getUnPergedCount() {
		return unPergedCount;
	}
	
	public void setUnPergedCount(Long unPergedCount) {
		this.unPergedCount = unPergedCount;
	}
	
	public boolean getCheckDoubleOptin() {
		return checkDoubleOptin;
	}
	public void setCheckDoubleOptin(boolean checkDoubleOptin) {
		this.checkDoubleOptin = checkDoubleOptin;
	}
	
	public Long getCustTemplateId() {
		return custTemplateId;
	}
	public void setCustTemplateId(Long custTemplateId) {
		this.custTemplateId = custTemplateId;
	}
	public Set<SMSCampaigns> getSmsCampaigns() {
		return smsCampaigns;
	}
	public void setSmsCampaigns(Set<SMSCampaigns> smsCampaigns) {
		this.smsCampaigns = smsCampaigns;
	}

	public String getListType() {
		return listType;
	}

	public void setListType(String listType) {
		this.listType = listType;
	}

	public boolean isCheckLoyaltyOptin() {
		return checkLoyaltyOptin;
	}

	public void setCheckLoyaltyOptin(boolean checkLoyaltyOptin) {
		this.checkLoyaltyOptin = checkLoyaltyOptin;
	}

	public Long getLoyaltyCutomTempId() {
		return loyaltyCutomTempId;
	}

	public void setLoyaltyCutomTempId(Long loyaltyCutomTempId) {
		this.loyaltyCutomTempId = loyaltyCutomTempId;
	}
	
	public Long getMlBit() {
		return mlBit;
	}

	public void setMlBit(Long mlBit) {
		this.mlBit = mlBit;
	}

	//added for sharing
	 public Set<UsersDomains> getSharedToDomain() {
		return sharedToDomain;
	}

	public void setSharedToDomain(Set<UsersDomains> sharedToDomain) {
		this.sharedToDomain = sharedToDomain;
	}
	
	
	public MailingList getMlCopy(){
		MailingList mList = new MailingList();
		
		//mList.setListId(this.listId);
		//mList.setListName(this.listName);
		mList.setListType(this.listType);
		mList.setLoyaltyCutomTempId(this.loyaltyCutomTempId);
		mList.setStatus(this.status);
		mList.setCheckDoubleOptin(this.checkDoubleOptin);
		mList.setCheckLoyaltyOptin(this.checkLoyaltyOptin);
		mList.setCheckParentalConsent(this.checkParentalConsent);
		mList.setCheckWelcomeMsg(this.checkWelcomeMsg);
		mList.setConsent(this.consent);
		mList.setCreatedDate(Calendar.getInstance());
		mList.setLastModifiedDate(Calendar.getInstance());
		mList.setDescription(this.description);
		mList.setCustTemplateId(this.custTemplateId);
		mList.setConsentCutomTempId(this.consentCutomTempId);
		mList.setSize(this.size);
		mList.setUnPergedCount(this.unPergedCount);
		//mList.setUsers(this.users.getParentUser() != null ? this.users.getParentUser() : this.users);
		mList.setUsers(this.users);
		mList.setListSize(this.listSize);
		mList.setWelcomeCustTempId(this.welcomeCustTempId);
		
		
		
		return mList;
	}

	/**
	 * @return the listSize
	 */
	public Long getListSize() {
		return listSize;
	}

	/**
	 * @param listSize the listSize to set
	 */
	public void setListSize(Long listSize) {
		this.listSize = listSize;
	}
}


