package org.mq.marketer.campaign.beans;

import java.util.Calendar;

/**
 * Clicks generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class NotificationClicks  implements java.io.Serializable {


     private Long clickId;
     private Long notificationCrId;
     private Long sentId;
     private String clickUrl;
     private Calendar clickDate;
     private String userAgent;

    public NotificationClicks() {
    }

	
    public NotificationClicks(Long sentId) {
        this.sentId = sentId;
    }
    public NotificationClicks(Long sentId, String clickUrl, Calendar clickDate, String userAgent) {
       this.sentId = sentId;
       this.clickUrl = clickUrl;
       this.clickDate = clickDate;
       this.userAgent = userAgent;
    }
   
    public Long getClickId() {
        return this.clickId;
    }
    
    public void setClickId(Long clickId) {
        this.clickId = clickId;
    }
    
    
    public Long getNotificationCrId() {
		return notificationCrId;
	}


	public void setNotificationCrId(Long crId) {
		this.notificationCrId = crId;
	}


	public Long getSentId() {
        return this.sentId;
    }
    
    public void setSentId(Long sentId) {
        this.sentId = sentId;
    }
    public String getClickUrl() {
        return this.clickUrl;
    }
    
    public void setClickUrl(String clickUrl) {
        this.clickUrl = clickUrl;
    }
    public Calendar getClickDate() {
        return this.clickDate;
    }
    
    public void setClickDate(Calendar clickDate) {
        this.clickDate = clickDate;
    }


	public String getUserAgent() {
		return userAgent;
	}


	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}




}



