package org.mq.marketer.campaign.beans;

import java.util.Calendar;


// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1



/**
 * Opens generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class Opens  implements java.io.Serializable {


     private Long openId;
     private Long sentId;
     private Calendar openDate;
     private Long emailClient;
     
     private String userAgent;//dummy string to set the email-client/browser/OS
     
    

	private Long osFamily;
   
	 private Long uaFamily;
  
     

    public Opens() {
    }

    public Opens(Long sentId, Calendar openDate,Long emailClient) {
    	 this.sentId = sentId;
         this.openDate = openDate;
         this.emailClient = emailClient;
    }

    public Opens(Long sentId, Calendar openDate,Long emailClient,Long osFamily,Long uaFamily) {
        this.sentId = sentId;
        this.openDate = openDate;
        this.emailClient = emailClient;
        this.osFamily=osFamily;
        this.uaFamily=uaFamily;
     }
	
    public Opens(Long sentId) {
        this.sentId = sentId;
    }
    public Opens(Long sentId, Calendar openDate, String userAgent) {
       this.sentId = sentId;
       this.openDate = openDate;
       this.userAgent = userAgent;
    }
   
    public Long getOpenId() {
        return this.openId;
    }
    
    public void setOpenId(Long openId) {
        this.openId = openId;
    }
    public Long getSentId() {
        return this.sentId;
    }
    
    public void setSentId(Long sentId) {
        this.sentId = sentId;
    }
    public Calendar getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Calendar openDate) {
        this.openDate = openDate;
    }

	public Long getEmailClient() {
		return emailClient;
	}

	public void setEmailClient(Long emailClient) {
		this.emailClient = emailClient;
	}

	public String getUserAgent() {
		return userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	 public Long getOsFamily() {
		return osFamily;
	}

	public void setOsFamily(Long osFamily) {
		this.osFamily = osFamily;
	}

	public Long getUaFamily() {
		return uaFamily;
	}

	public void setUaFamily(Long uaFamily) {
		this.uaFamily = uaFamily;
	}
	/*@Override
	public int compareTo(Object obj) {
		
		if(obj == null) 
			return 1;
		
		if(obj instanceof Opens) {
			
			Opens open = (Opens)obj;
			return open.openDate.compareTo(this.openDate);
		} 
		else {
			return 1;
		}
		
	}*/
	
}


