package org.mq.marketer.campaign.beans;

import java.util.Calendar;

// Generated 28 Jan, 2010 3:08:13 PM by Hibernate Tools 3.2.0.CR1



/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Long scheduleId;
     private Campaigns campaign;
     private String frequencyType;
     private String frequency;
     private Calendar startDate;
     private Calendar endDate;
     private int day;

    public Schedule() {
    }

	
    public Schedule(Campaigns campaign) {
        this.campaign = campaign;
    }
    public Schedule(Campaigns campaign, String frequencyType, String frequency, Calendar startDate, Calendar endDate, int day) {
       this.campaign = campaign;
       this.frequencyType = frequencyType;
       this.frequency = frequency;
       this.startDate = startDate;
       this.endDate = endDate;
       this.day = day;
    }
   
    public static Schedule copySchedule(Schedule srcSchedule, Schedule destSchedule){
    	destSchedule.setDay(srcSchedule.getDay());
    	destSchedule.setEndDate(srcSchedule.getEndDate());
    	destSchedule.setFrequency(srcSchedule.getFrequency());
    	destSchedule.setFrequencyType(srcSchedule.getFrequencyType());
    	destSchedule.setStartDate(srcSchedule.getStartDate());
    	return destSchedule;
    }
   
    public Long getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(Long scheduleId) {
        this.scheduleId = scheduleId;
    }
    public Campaigns getCampaign() {
        return this.campaign;
    }
    
    public void setCampaign(Campaigns campaign) {
        this.campaign = campaign;
    }
    public String getFrequencyType() {
        return this.frequencyType;
    }
    
    public void setFrequencyType(String frequencyType) {
        this.frequencyType = frequencyType;
    }
    public String getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }
    public Calendar getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Calendar startDate) {
        this.startDate = startDate;
    }
    public Calendar getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Calendar endDate) {
        this.endDate = endDate;
    }
    public int getDay() {
        return this.day;
    }
    
    public void setDay(int day) {
        this.day = day;
    }
}