package org.mq.marketer.campaign.beans;

import java.util.Calendar;

// Generated 14 May, 2009 12:22:57 PM by Hibernate Tools 3.2.0.CR1



/**
 * SystemTemplates generated by hbm2java
 */
@SuppressWarnings({ "unchecked", "serial" })
public class SystemTemplates  implements java.io.Serializable {


     private Long templateId;
     private String name;
     private String divisions;
     private String htmlText;
     private Calendar createdDate;
     private TemplateCategory templateCategory;
     private String dirName;
     private String jsonText;

    public String getJsonText() {
		return jsonText;
	}


	public void setJsonText(String jsonText) {
		this.jsonText = jsonText;
	}


	public SystemTemplates() {
    }

	
    public SystemTemplates(String name, TemplateCategory templateCategory) {
        this.name = name;
        this.templateCategory = templateCategory;
    }
    public SystemTemplates(String name,Calendar createdDate, TemplateCategory templateCategory) {
       this.name = name;
       this.createdDate = createdDate;
       this.templateCategory = templateCategory;
    }
   
    public Long getTemplateId() {
        return this.templateId;
    }
    
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getDivisions() {
        return this.divisions;
    }
    
    public void setDivisions(String divisions) {
        this.divisions = divisions;
    }
    
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }

    public TemplateCategory getTemplateCategory() {
        return this.templateCategory;
    }
    
    public void setTemplateCategory(TemplateCategory templateCategory) {
        this.templateCategory = templateCategory;
    }

	public String getHtmlText() {
		return htmlText;
	}

	public void setHtmlText(String htmlText) {
		this.htmlText = htmlText;
	}


	public String getDirName() {
		return dirName;
	}

	public void setDirName(String dirName) {
		this.dirName = dirName;
	}

}


