package org.mq.marketer.campaign.beans;

import java.util.Calendar;

// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1



/**
 * TemplateCategory generated by hbm2java
 */
@SuppressWarnings("serial")
public class TemplateCategory  implements java.io.Serializable {


     private Long id;
     private String categoryName;
     private Calendar cratedDate;
     private String dirName;
     
     /**
      * The following variables are used in unsubscribe case to represent whether the recipient <BR>
      * unsubscribed for this category.
      */
     private boolean selected;
     private short weightage;
     
	public TemplateCategory() {
    }

	
    public TemplateCategory(String categoryName) {
        this.categoryName = categoryName;
    }
    public TemplateCategory(String categoryName, Calendar cratedDate) {
       this.categoryName = categoryName;
       this.cratedDate = cratedDate;
    }
    
    public TemplateCategory(String categoryName, boolean selected) {
    	this.categoryName = categoryName;
    	this.selected = selected;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Calendar getCratedDate() {
        return this.cratedDate;
    }
    
    public void setCratedDate(Calendar cratedDate) {
        this.cratedDate = cratedDate;
    }

    public String getDirName() {
		return dirName;
	}

	public void setDirName(String dirName) {
		this.dirName = dirName;
	}


	public boolean isSelected() {
		return selected;
	}

	public boolean getSelected() {
		return selected;
	}
	
	public void setSelected(boolean selected) {
		this.selected = selected;
	}
	
	public short getWeightage() {
		return weightage;
	}


	public void setWeightage(short weightage) {
		this.weightage = weightage;
	}

}


