package org.mq.marketer.campaign.beans;

import java.util.Calendar;

// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1



/**
 * UploadReport generated by hbm2java
 */
public class UploadReport  implements java.io.Serializable {


     private Long uploadReportId;
     private String fileName;
     private String uploadedTo;
     private String module;
     private Calendar date;
     private String report;
     private String status;

    public UploadReport() {
    }

	
    public UploadReport(String fileName) {
        this.fileName = fileName;
    }
    public UploadReport(String fileName, String uploadedTo, Calendar date, String report, String status) {
       this.fileName = fileName;
       this.uploadedTo = uploadedTo;
       this.date = date;
       this.report = report;
       this.status = status;
    }
   
    public Long getUploadReportId() {
        return this.uploadReportId;
    }
    
    public void setUploadReportId(Long id) {
        this.uploadReportId = id;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
	public String getUploadedTo() {
		return uploadedTo;
	}

	public void setUploadedTo(String uploadedTo) {
		this.uploadedTo = uploadedTo;
	}
	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}
    
     public Calendar getDate() {
        return this.date;
    }
    
    public void setDate(Calendar date) {
        this.date = date;
    }
    public String getReport() {
        return this.report;
    }
    
    public void setReport(String report) {
        this.report = report;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


}


