package org.mq.marketer.campaign.beans;


// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1



/**
 * UserFromEmailId generated by hbm2java
 */
public class UserFromEmailId  implements java.io.Serializable {


     private Long id;
     private Users users;
     private String emailId;
     private int status;

    public UserFromEmailId() {
    }

    public UserFromEmailId(Users users, String emailId, int status) {
       this.users = users;
       this.emailId = emailId;
       this.status = status;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

}


