package org.mq.loyality.common.hbmbean;

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
/**
 * Contacts generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class Contacts  implements java.io.Serializable {


     private Long contactId;
     //private MailingList mailingList;
     
     //private Set<MailingList> mlSet = new HashSet<MailingList>(0);
     //private Set mlSet;
     private Users user;
     
     private String emailId;
     private String firstName;
     private String lastName;
     private Calendar createdDate;
     private Boolean purged = false;
     private String emailStatus;
     private Calendar lastStatusChange;
     private Calendar lastMailDate;
     private String addressOne;
     private String addressTwo;
     private String city;
     private String state;
     private String country;
     private int pin;
     private Long phone;
     private Byte optin;
     private String subscriptionType;
     private String mobileStatus;
     private String udf2;
     private String udf3;
     private String udf4;
     private String udf5;
     private String udf6;
     private String udf7;
     private String udf8;
     private String udf9;
     private String udf10;
     private String udf11;
     private String udf12;
     private String udf13;
     private String udf14;
     private String udf15;
	private String gender;
	private Calendar birthDay;
	private Calendar anniversary;
	private Byte optedInto;
	private Byte optinPerType;
	private String optinMedium;
	private String activityDate;
	private String externalId;
	private String homeStore;
	private Long hpId;
     private Byte loyaltyCustomer;
     
    private String zip;
    private String mobilePhone;
    private String homePhone; 

	private Calendar lastSMSDate;
	private boolean mobileOptin;
	private boolean mark;
	
	private String stringBirthDay;
	private String stringAnniversary;

	
	private String usState;
	

	
	public String getStringAnniversary() {
		return stringAnniversary;
	}
	public void setStringAnniversary(String stringAnniversary) {
		this.stringAnniversary = stringAnniversary;
	}
	public String getStringBirthDay() {
		return stringBirthDay;
	}
	public void setStringBirthDay(String stringBirthDay) {
		this.stringBirthDay = stringBirthDay;
	}
	public boolean isMark() {
		return mark;
	}

	public void setMark(boolean mark) {
		this.mark = mark;
	}


	private Long mlBits;
	private String categories;
	private int lastMailSpan;
	private int lastSmsSpan;
	private String birthYear;
	private String birthDay1;
	private String birthMonth;
	private String annDay;
	private String annYear;
	private String annMonth;
	
	
	
	public String getBirthYear() {
		return birthYear;
	}
	public void setBirthYear(String birthYear) {
		this.birthYear = birthYear;
	}
	public String getBirthDay1() {
		return birthDay1;
	}
	public void setBirthDay1(String birthDay1) {
		this.birthDay1 = birthDay1;
	}
	public String getBirthMonth() {
		return birthMonth;
	}
	public void setBirthMonth(String birthMonth) {
		this.birthMonth = birthMonth;
	}
	public String getAnnDay() {
		return annDay;
	}
	public void setAnnDay(String annDay) {
		this.annDay = annDay;
	}
	public String getAnnYear() {
		return annYear;
	}
	public void setAnnYear(String annYear) {
		this.annYear = annYear;
	}
	public String getAnnMonth() {
		return annMonth;
	}
	public void setAnnMonth(String annMonth) {
		this.annMonth = annMonth;
	}


	private Calendar mobileOptinDate;
	private String mobileOptinSource;
	
	public Calendar getMobileOptinDate() {
		return mobileOptinDate;
	}

	public void setMobileOptinDate(Calendar mobileOptinDate) {
		this.mobileOptinDate = mobileOptinDate;
	}

	public String getMobileOptinSource() {
		return mobileOptinSource;
	}

	public void setMobileOptinSource(String mobileOptinSource) {
		this.mobileOptinSource = mobileOptinSource;
	}



	public void setUdf1(String udf1) {
		this.udf1 = udf1;
	}

	public void setUdf2(String udf2) {
		this.udf2 = udf2;
	}

	public void setUdf3(String udf3) {
		this.udf3 = udf3;
	}

	public void setUdf4(String udf4) {
		this.udf4 = udf4;
	}

	public void setUdf5(String udf5) {
		this.udf5 = udf5;
	}

	public void setUdf6(String udf6) {
		this.udf6 = udf6;
	}

	public void setUdf7(String udf7) {
		this.udf7 = udf7;
	}

	public void setUdf8(String udf8) {
		this.udf8 = udf8;
	}

	public void setUdf9(String udf9) {
		this.udf9 = udf9;
	}

	public void setUdf10(String udf10) {
		this.udf10 = udf10;
	}

	public void setUdf11(String udf11) {
		this.udf11 = udf11;
	}

	public void setUdf12(String udf12) {
		this.udf12 = udf12;
	}

	public void setUdf13(String udf13) {
		this.udf13 = udf13;
	}

	public void setUdf14(String udf14) {
		this.udf14 = udf14;
	}

	public void setUdf15(String udf15) {
		this.udf15 = udf15;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}


	private String udf1;
	     public String getUdf1() {
		return udf1;
	}
	
	public String getUdf2() {
		return udf2;
	}
	
	public String getUdf3() {
		return udf3;
	}
	
	public String getUdf4() {
		return udf4;
	}
	
	public String getUdf5() {
		return udf5;
	}
	
	public String getUdf6() {
		return udf6;
	}
	
	public String getUdf7() {
		return udf7;
	}
	
	public String getUdf8() {
		return udf8;
	}
	
	public String getUdf9() {
		return udf9;
	}
	
	public String getUdf10() {
		return udf10;
	}
	
	public String getUdf11() {
		return udf11;
	}
	
	public String getUdf12() {
		return udf12;
	}
	
	public String getUdf13() {
		return udf13;
	}
	
	public String getUdf14() {
		return udf14;
	}
	
	public String getUdf15() {
		return udf15;
	}
	
	public String getGender() {
		return gender;
	}


	

     public Calendar getBirthDay() {
    	 return birthDay;
     }

	public void setBirthDay(Calendar birthDay) {
		this.birthDay = birthDay;
	}
	
	public Calendar getAnniversary() {
		return anniversary;
	}
	
	public void setAnniversary(Calendar anniversary) {
		this.anniversary = anniversary;
	}
	
	public Byte getOptedInto() {
		return optedInto;
	}

	public void setOptedInto(Byte optedInto) {
		this.optedInto = optedInto;
	}
	
	public Byte getOptinPerType() {
		return optinPerType;
	}
	
	public void setOptinPerType(Byte optinPerType) {
		this.optinPerType = optinPerType;
	}


	 
     


	public String getExternalId() {
		return externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}
	
	

	public String getOptinMedium() {
		return optinMedium;
	}

	public void setOptinMedium(String optinMedium) {
		this.optinMedium = optinMedium;
	}

    
    
/*    public Contacts(Contacts contact) {
        this.mailingList = contact.getMailingList();
        this.emailId = contact.getEmailId();
        this.firstName = contact.getFirstName();
        this.lastName = contact.getLastName();
        this.createdDate = new Date();
        this.optinStatus = contact.getOptinStatus();
        this.emailStatus = contact.getEmailStatus();
        this.addressOne = contact.getAddressOne();
        this.addressTwo = contact.getAddressTwo();
        this.city = contact.getCity();
        this.state = contact.getState();
        this.country = contact.getCountry();
        this.pin = contact.getPin();
        this.phone = contact.getPhone();
        this.optin = contact.getOptin();
        this.subscriptionType = contact.getSubscriptionType();
    }*/
	

	/*public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, 
			Calendar createdDate, Boolean purged, String emailStatus, Calendar lastStatusChange) {
       this.mailingList = mailingList;
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.purged = purged;
       this.emailStatus = emailStatus;
       this.lastStatusChange = lastStatusChange;
    }*/

   /* public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, 
    		Calendar createdDate, Boolean purged, String emailStatus, Calendar lastStatusChange, 
    		Calendar lastMailDate, String addressOne, String addressTwo, String city, String state,
    		String country, int pin, Long phone,byte optin,String subscriptionType) {
    	
       this.mailingList = mailingList;
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.purged = purged;
       this.emailStatus = emailStatus;
       this.lastStatusChange = lastStatusChange;
       this.lastMailDate = lastMailDate;
       this.addressOne = addressOne;
       this.addressTwo = addressTwo;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pin = pin;
       this.phone = phone;
       this.optin = optin;
       this.subscriptionType = subscriptionType;
    }*/
    
  /*  public Contacts(MailingList mailingList, String emailId, String firstName,
    		String lastName, Calendar createdDate, Boolean purged, String emailStatus,
    		String addressOne, String addressTwo, String city, String state, String country,
    		int pin, Long phone) {
    	
       this.mailingList = mailingList;
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.purged = purged;
       this.emailStatus = emailStatus;
       this.addressOne = addressOne;
       this.addressTwo = addressTwo;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pin = pin;
       this.phone = phone;
    }*/
   
  /*  public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, 
    		Calendar createdDate, Boolean purged, String emailStatus, Calendar lastStatusChange,
    		String addressOne, String addressTwo, String city, String state, String country, int pin,
    		Long phone) {
    	
       this.mailingList = mailingList;
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.purged = purged;
       this.emailStatus = emailStatus;
       this.lastStatusChange = lastStatusChange;
       this.addressOne = addressOne;
       this.addressTwo = addressTwo;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pin = pin;
       this.phone = phone;
    }*/
   
    public Long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }
    
   /* public MailingList getMailingList() {
        return this.mailingList;
    }*/
   /* public MailingList getMailingListByType(String listType) {
        
    	if(this.getContactBit() == null) return null;
    	
    	Iterator<MailingList> listIt = this.mlSet.iterator();
    	MailingList tempList = null;
    	while(listIt.hasNext()){
    		tempList = listIt.next();
    		if(tempList.getListType().equals(listType)) return tempList;
    	}
    	return null;
    }//getMailingListByType
*/    
    /*public void setMailingList(MailingList mailingList) {
        this.mailingList = mailingList;
        //this.mlSet.add(mailingList);
    }*/
    
   /* public Set<MailingList> getMlSet() {
		return mlSet;
	}

	public void setMlSet(Set<MailingList> mlSet) {
		this.mlSet = mlSet;
	}*/
	public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    public Boolean getPurged() {
        return this.purged;
    }
    
    public void setPurged(Boolean purged) {
        this.purged = purged;
    }
    public String getEmailStatus() {
        return this.emailStatus;
    }
    
    public void setEmailStatus(String emailStatus) {
        this.emailStatus = emailStatus;
    }
    public Calendar getLastMailDate() {
        return this.lastMailDate;
    }
    
    public void setLastMailDate(Calendar lastMailDate) {
        this.lastMailDate = lastMailDate;
    }

    public Calendar getLastStatusChange() {
        return this.lastStatusChange;
    }
    
    public void setLastStatusChange(Calendar lastStatusChange) {
        this.lastStatusChange = lastStatusChange;
    }
    public String getAddressOne() {
        return this.addressOne;
    }
    
    public void setAddressOne(String addressOne) {
        this.addressOne = addressOne;
    }
    public String getAddressTwo() {
        return this.addressTwo;
    }
    
    public void setAddressTwo(String addressTwo) {
        this.addressTwo = addressTwo;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public int getPin() {
        return this.pin;
    }
    
    public void setPin(int pin) {
        this.pin = pin;
    }
    public Long getPhone() {
        return this.phone;
    }
    
    public void setPhone(Long phone) {
        this.phone = phone;
    }

	public Byte getOptin() {
		return optin;
	}

	public void setOptin(Byte optin) {
		this.optin = optin;
	}

	public String getSubscriptionType() {
		return subscriptionType;
	}

	public void setSubscriptionType(String subscriptionType) {
		this.subscriptionType = subscriptionType;
	}
	
	
	
	 public Long getHpId() {
		return hpId;
	}

	public void setHpId(Long hpId) {
		this.hpId = hpId;
	}

	public Byte getLoyaltyCustomer() {
		return loyaltyCustomer;
	}

	public void setLoyaltyCustomer(Byte loyaltyCustomer) {
		this.loyaltyCustomer = loyaltyCustomer;
	}
	/*public Object getScore() {
		return score;
	}
	
	public void setScore(Object score) {
		this.score = score;
	}
	*/
/*	@Override
	public String toString() {
		// TODO Auto-generated method stub
		StringBuffer contactSb = new StringBuffer();
		contactSb.append(contactId);
		contactSb.append(", ");
		
		
		//String contactInfo = contactId + "," + mailingList + ", " + emailId + ", " + firstName + ", " + lastName + ", " + createdDate + ", " + optinStatus + ", " + emailStatus + ", " + lastStatusChange + ", " + lastMailDate + ", " + addressOne + ", " + addressTwo + ", " + city + ", " + state + ", " + country + ", " + pin + ", " + phone + ", " + optin + ", " + subscriptionType;
		String contactInfo = emailId + ", " + firstName + ", " + lastName + ", " + addressOne + ", " + addressTwo + ", " + city + ", " + state + ", " + country + ", " + pin + ", " + phone;
		return contactInfo;
	}
	*/
	
	
	public String getActivityDate() {
		return activityDate;
	}

	public void setActivityDate(String activityDate) {
		this.activityDate = activityDate;
	}

	public String getHomeStore() {
		return homeStore;
	}

	public void setHomeStore(String homeStore) {
		this.homeStore = homeStore;
	}

	public String getMobileStatus() {
		return mobileStatus;
	}

	public void setMobileStatus(String mobileStatus) {
		this.mobileStatus = mobileStatus;
	}

	

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getHomePhone() {
		return homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}


public Calendar getLastSMSDate() {
		return lastSMSDate;
	}

	public void setLastSMSDate(Calendar lastSMSDate) {
		this.lastSMSDate = lastSMSDate;
	}

	public boolean isMobileOptin() {
		return mobileOptin;
	}

	public void setMobileOptin(boolean mobileOptin) {
		this.mobileOptin = mobileOptin;
	}

	public Long getMlBits() {
		return mlBits;
	}

	public void setMlBits(Long mlBits) {
		this.mlBits = mlBits;
	}

	public String getCategories() {
		return categories;
	}

	public void setCategories(String categories) {
		this.categories = categories;
	}

	public int getLastMailSpan() {
		return lastMailSpan;
	}

	public void setLastMailSpan(int lastMailSpan) {
		this.lastMailSpan = lastMailSpan;
	}

	public int getLastSmsSpan() {
		return lastSmsSpan;
	}

	public void setLastSmsSpan(int lastSmsSpan) {
		this.lastSmsSpan = lastSmsSpan;
	}
	public String getUsState() {
		return usState;
	}
	public void setUsState(String usState) {
		this.usState = usState;
	}
	public Users getUser() {
		return user;
	}
	public void setUser(Users user) {
		this.user = user;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((user == null)? 0 : user.hashCode());
		result = prime * result
				+ ((activityDate == null) ? 0 : activityDate.hashCode());
		result = prime * result
				+ ((addressOne == null) ? 0 : addressOne.hashCode());
		result = prime * result
				+ ((addressTwo == null) ? 0 : addressTwo.hashCode());
		result = prime * result + ((annDay == null) ? 0 : annDay.hashCode());
		result = prime * result
				+ ((annMonth == null) ? 0 : annMonth.hashCode());
		result = prime * result + ((annYear == null) ? 0 : annYear.hashCode());
		result = prime * result
				+ ((anniversary == null) ? 0 : anniversary.hashCode());
		result = prime * result
				+ ((birthDay == null) ? 0 : birthDay.hashCode());
		result = prime * result
				+ ((birthDay1 == null) ? 0 : birthDay1.hashCode());
		result = prime * result
				+ ((birthMonth == null) ? 0 : birthMonth.hashCode());
		result = prime * result
				+ ((birthYear == null) ? 0 : birthYear.hashCode());
		result = prime * result
				+ ((categories == null) ? 0 : categories.hashCode());
		result = prime * result + ((city == null) ? 0 : city.hashCode());
		result = prime * result
				+ ((contactId == null) ? 0 : contactId.hashCode());
		result = prime * result + ((country == null) ? 0 : country.hashCode());
		result = prime * result
				+ ((createdDate == null) ? 0 : createdDate.hashCode());
		result = prime * result + ((emailId == null) ? 0 : emailId.hashCode());
		result = prime * result
				+ ((emailStatus == null) ? 0 : emailStatus.hashCode());
		result = prime * result
				+ ((externalId == null) ? 0 : externalId.hashCode());
		result = prime * result
				+ ((firstName == null) ? 0 : firstName.hashCode());
		result = prime * result + ((gender == null) ? 0 : gender.hashCode());
		result = prime * result
				+ ((homePhone == null) ? 0 : homePhone.hashCode());
		result = prime * result
				+ ((homeStore == null) ? 0 : homeStore.hashCode());
		result = prime * result + ((hpId == null) ? 0 : hpId.hashCode());
		result = prime * result
				+ ((lastMailDate == null) ? 0 : lastMailDate.hashCode());
		result = prime * result + lastMailSpan;
		result = prime * result
				+ ((lastName == null) ? 0 : lastName.hashCode());
		result = prime * result
				+ ((lastSMSDate == null) ? 0 : lastSMSDate.hashCode());
		result = prime * result + lastSmsSpan;
		result = prime
				* result
				+ ((lastStatusChange == null) ? 0 : lastStatusChange.hashCode());
		result = prime * result
				+ ((loyaltyCustomer == null) ? 0 : loyaltyCustomer.hashCode());
		result = prime * result + (mark ? 1231 : 1237);
		result = prime * result + ((mlBits == null) ? 0 : mlBits.hashCode());
		result = prime * result + (mobileOptin ? 1231 : 1237);
		result = prime * result
				+ ((mobileOptinDate == null) ? 0 : mobileOptinDate.hashCode());
		result = prime
				* result
				+ ((mobileOptinSource == null) ? 0 : mobileOptinSource
						.hashCode());
		result = prime * result
				+ ((mobilePhone == null) ? 0 : mobilePhone.hashCode());
		result = prime * result
				+ ((mobileStatus == null) ? 0 : mobileStatus.hashCode());
		result = prime * result
				+ ((optedInto == null) ? 0 : optedInto.hashCode());
		result = prime * result + ((optin == null) ? 0 : optin.hashCode());
		result = prime * result
				+ ((optinMedium == null) ? 0 : optinMedium.hashCode());
		result = prime * result
				+ ((optinPerType == null) ? 0 : optinPerType.hashCode());
		result = prime * result + ((phone == null) ? 0 : phone.hashCode());
		result = prime * result + pin;
		result = prime * result + ((purged == null) ? 0 : purged.hashCode());
		result = prime * result + ((state == null) ? 0 : state.hashCode());
		result = prime
				* result
				+ ((stringAnniversary == null) ? 0 : stringAnniversary
						.hashCode());
		result = prime * result
				+ ((stringBirthDay == null) ? 0 : stringBirthDay.hashCode());
		result = prime
				* result
				+ ((subscriptionType == null) ? 0 : subscriptionType.hashCode());
		result = prime * result + ((udf1 == null) ? 0 : udf1.hashCode());
		result = prime * result + ((udf10 == null) ? 0 : udf10.hashCode());
		result = prime * result + ((udf11 == null) ? 0 : udf11.hashCode());
		result = prime * result + ((udf12 == null) ? 0 : udf12.hashCode());
		result = prime * result + ((udf13 == null) ? 0 : udf13.hashCode());
		result = prime * result + ((udf14 == null) ? 0 : udf14.hashCode());
		result = prime * result + ((udf15 == null) ? 0 : udf15.hashCode());
		result = prime * result + ((udf2 == null) ? 0 : udf2.hashCode());
		result = prime * result + ((udf3 == null) ? 0 : udf3.hashCode());
		result = prime * result + ((udf4 == null) ? 0 : udf4.hashCode());
		result = prime * result + ((udf5 == null) ? 0 : udf5.hashCode());
		result = prime * result + ((udf6 == null) ? 0 : udf6.hashCode());
		result = prime * result + ((udf7 == null) ? 0 : udf7.hashCode());
		result = prime * result + ((udf8 == null) ? 0 : udf8.hashCode());
		result = prime * result + ((udf9 == null) ? 0 : udf9.hashCode());
		result = prime * result + ((usState == null) ? 0 : usState.hashCode());
		result = prime * result + ((zip == null) ? 0 : zip.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Contacts other = (Contacts) obj;
		if (activityDate == null) {
			if (other.activityDate != null)
				return false;
		} else if (!activityDate.equals(other.activityDate))
			return false;
		if (addressOne == null) {
			if (other.addressOne != null)
				return false;
		} else if (!addressOne.equals(other.addressOne))
			return false;
		if (addressTwo == null) {
			if (other.addressTwo != null)
				return false;
		} else if (!addressTwo.equals(other.addressTwo))
			return false;
		if (annDay == null) {
			if (other.annDay != null)
				return false;
		} else if (!annDay.equals(other.annDay))
			return false;
		if (annMonth == null) {
			if (other.annMonth != null)
				return false;
		} else if (!annMonth.equals(other.annMonth))
			return false;
		if (annYear == null) {
			if (other.annYear != null)
				return false;
		} else if (!annYear.equals(other.annYear))
			return false;
		if (anniversary == null) {
			if (other.anniversary != null)
				return false;
		} else if (!anniversary.equals(other.anniversary))
			return false;
		if (birthDay == null) {
			if (other.birthDay != null)
				return false;
		} else if (!birthDay.equals(other.birthDay))
			return false;
		if (birthDay1 == null) {
			if (other.birthDay1 != null)
				return false;
		} else if (!birthDay1.equals(other.birthDay1))
			return false;
		if (birthMonth == null) {
			if (other.birthMonth != null)
				return false;
		} else if (!birthMonth.equals(other.birthMonth))
			return false;
		if (birthYear == null) {
			if (other.birthYear != null)
				return false;
		} else if (!birthYear.equals(other.birthYear))
			return false;
		if (categories == null) {
			if (other.categories != null)
				return false;
		} else if (!categories.equals(other.categories))
			return false;
		if (city == null) {
			if (other.city != null)
				return false;
		} else if (!city.equals(other.city))
			return false;
		if (contactId == null) {
			if (other.contactId != null)
				return false;
		} else if (!contactId.equals(other.contactId))
			return false;
		if (country == null) {
			if (other.country != null)
				return false;
		} else if (!country.equals(other.country))
			return false;
		if (createdDate == null) {
			if (other.createdDate != null)
				return false;
		} else if (!createdDate.equals(other.createdDate))
			return false;
		if (emailId == null) {
			if (other.emailId != null)
				return false;
		} else if (!emailId.equals(other.emailId))
			return false;
		if (emailStatus == null) {
			if (other.emailStatus != null)
				return false;
		} else if (!emailStatus.equals(other.emailStatus))
			return false;
		if (externalId == null) {
			if (other.externalId != null)
				return false;
		} else if (!externalId.equals(other.externalId))
			return false;
		if (firstName == null) {
			if (other.firstName != null)
				return false;
		} else if (!firstName.equals(other.firstName))
			return false;
		if (gender == null) {
			if (other.gender != null)
				return false;
		} else if (!gender.equals(other.gender))
			return false;
		if (homePhone == null) {
			if (other.homePhone != null)
				return false;
		} else if (!homePhone.equals(other.homePhone))
			return false;
		if (homeStore == null) {
			if (other.homeStore != null)
				return false;
		} else if (!homeStore.equals(other.homeStore))
			return false;
		if (hpId == null) {
			if (other.hpId != null)
				return false;
		} else if (!hpId.equals(other.hpId))
			return false;
		if (lastMailDate == null) {
			if (other.lastMailDate != null)
				return false;
		} else if (!lastMailDate.equals(other.lastMailDate))
			return false;
		if (lastMailSpan != other.lastMailSpan)
			return false;
		if (lastName == null) {
			if (other.lastName != null)
				return false;
		} else if (!lastName.equals(other.lastName))
			return false;
		if (lastSMSDate == null) {
			if (other.lastSMSDate != null)
				return false;
		} else if (!lastSMSDate.equals(other.lastSMSDate))
			return false;
		if (lastSmsSpan != other.lastSmsSpan)
			return false;
		if (lastStatusChange == null) {
			if (other.lastStatusChange != null)
				return false;
		} else if (!lastStatusChange.equals(other.lastStatusChange))
			return false;
		if (loyaltyCustomer == null) {
			if (other.loyaltyCustomer != null)
				return false;
		} else if (!loyaltyCustomer.equals(other.loyaltyCustomer))
			return false;
		if (mark != other.mark)
			return false;
		if (mlBits == null) {
			if (other.mlBits != null)
				return false;
		} else if (!mlBits.equals(other.mlBits))
			return false;
		if (mobileOptin != other.mobileOptin)
			return false;
		if (mobileOptinDate == null) {
			if (other.mobileOptinDate != null)
				return false;
		} else if (!mobileOptinDate.equals(other.mobileOptinDate))
			return false;
		if (mobileOptinSource == null) {
			if (other.mobileOptinSource != null)
				return false;
		} else if (!mobileOptinSource.equals(other.mobileOptinSource))
			return false;
		if (mobilePhone == null) {
			if (other.mobilePhone != null)
				return false;
		} else if (!mobilePhone.equals(other.mobilePhone))
			return false;
		if (mobileStatus == null) {
			if (other.mobileStatus != null)
				return false;
		} else if (!mobileStatus.equals(other.mobileStatus))
			return false;
		if (optedInto == null) {
			if (other.optedInto != null)
				return false;
		} else if (!optedInto.equals(other.optedInto))
			return false;
		if (optin == null) {
			if (other.optin != null)
				return false;
		} else if (!optin.equals(other.optin))
			return false;
		if (optinMedium == null) {
			if (other.optinMedium != null)
				return false;
		} else if (!optinMedium.equals(other.optinMedium))
			return false;
		if (optinPerType == null) {
			if (other.optinPerType != null)
				return false;
		} else if (!optinPerType.equals(other.optinPerType))
			return false;
		if (phone == null) {
			if (other.phone != null)
				return false;
		} else if (!phone.equals(other.phone))
			return false;
		if (pin != other.pin)
			return false;
		if (purged == null) {
			if (other.purged != null)
				return false;
		} else if (!purged.equals(other.purged))
			return false;
		if (state == null) {
			if (other.state != null)
				return false;
		} else if (!state.equals(other.state))
			return false;
		if (stringAnniversary == null) {
			if (other.stringAnniversary != null)
				return false;
		} else if (!stringAnniversary.equals(other.stringAnniversary))
			return false;
		if (stringBirthDay == null) {
			if (other.stringBirthDay != null)
				return false;
		} else if (!stringBirthDay.equals(other.stringBirthDay))
			return false;
		if (subscriptionType == null) {
			if (other.subscriptionType != null)
				return false;
		} else if (!subscriptionType.equals(other.subscriptionType))
			return false;
		if (udf1 == null) {
			if (other.udf1 != null)
				return false;
		} else if (!udf1.equals(other.udf1))
			return false;
		if (udf10 == null) {
			if (other.udf10 != null)
				return false;
		} else if (!udf10.equals(other.udf10))
			return false;
		if (udf11 == null) {
			if (other.udf11 != null)
				return false;
		} else if (!udf11.equals(other.udf11))
			return false;
		if (udf12 == null) {
			if (other.udf12 != null)
				return false;
		} else if (!udf12.equals(other.udf12))
			return false;
		if (udf13 == null) {
			if (other.udf13 != null)
				return false;
		} else if (!udf13.equals(other.udf13))
			return false;
		if (udf14 == null) {
			if (other.udf14 != null)
				return false;
		} else if (!udf14.equals(other.udf14))
			return false;
		if (udf15 == null) {
			if (other.udf15 != null)
				return false;
		} else if (!udf15.equals(other.udf15))
			return false;
		if (udf2 == null) {
			if (other.udf2 != null)
				return false;
		} else if (!udf2.equals(other.udf2))
			return false;
		if (udf3 == null) {
			if (other.udf3 != null)
				return false;
		} else if (!udf3.equals(other.udf3))
			return false;
		if (udf4 == null) {
			if (other.udf4 != null)
				return false;
		} else if (!udf4.equals(other.udf4))
			return false;
		if (udf5 == null) {
			if (other.udf5 != null)
				return false;
		} else if (!udf5.equals(other.udf5))
			return false;
		if (udf6 == null) {
			if (other.udf6 != null)
				return false;
		} else if (!udf6.equals(other.udf6))
			return false;
		if (udf7 == null) {
			if (other.udf7 != null)
				return false;
		} else if (!udf7.equals(other.udf7))
			return false;
		if (udf8 == null) {
			if (other.udf8 != null)
				return false;
		} else if (!udf8.equals(other.udf8))
			return false;
		if (udf9 == null) {
			if (other.udf9 != null)
				return false;
		} else if (!udf9.equals(other.udf9))
			return false;
		if (usState == null) {
			if (other.usState != null)
				return false;
		} else if (!usState.equals(other.usState))
			return false;
		if (zip == null) {
			if (other.zip != null)
				return false;
		} else if (!zip.equals(other.zip))
			return false;
		if (user == null) {
			if (other.user != null)
				return false;
		} else if (!user.equals(other.user))
			return false;
		return true;
	}
	
	
}

