package org.mq.loyality.common.hbmbean;


// Generated 14 Oct, 2009 6:21:14 PM by Hibernate Tools 3.2.0.CR1


import java.math.BigInteger;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable, Comparable<Users> {


	private static final long serialVersionUID = 1L;
	
	private Long userId;
	private String mqsId;
	private String userName;
	private String password;
	private String emailId;
	private String firstName;
	private String lastName;
	private String companyName;
	private Calendar createdDate;
	private String addressOne;
	private String addressTwo;
	private String city;
	private String state;
	private String country;
	private String pinCode;
	private String phone;
	private String vmta;
	private boolean enabled;
	private Integer emailCount;
	private Integer usedEmailCount;
	private Integer smsCount;
	private Integer usedSmsCount;
	private Calendar packageStartDate;
	private Calendar packageExpiryDate;
	private String userActivitySettings;
	private String token;
	private Byte footerEditor;
	
	private String accountType;
    
	
	private String userDomainStr;
	private String userRole;
	private String CIMProfileId;
	private String MsgChkType;
	private String userSMSTool;
    private Short countryCarrier;
//    private String countryCode;
    private String clientTimeZone;
	private boolean subscriptionEnable;
	private Calendar lastLoggedInTime;
		
	// Added for sms 
	private boolean enableSMS;
	private boolean considerSMSSettings;
	private String countryType;
	private Byte optInMedium;
	
	public String getCountryType() {
		return countryType;
	}

	public void setCountryType(String countryType) {
		this.countryType = countryType;
	}

		
	public Byte getOptInMedium() {
		return optInMedium;
	}
	public void setOptInMedium(Byte optInMedium) {
		this.optInMedium = optInMedium;
	}	
		
	public boolean isConsiderSMSSettings() {
		return considerSMSSettings;
	}

	public void setConsiderSMSSettings(boolean considerSMSSettings) {
		this.considerSMSSettings = considerSMSSettings;
	}

	public boolean getSubscriptionEnable() {
		return subscriptionEnable;
	}

	public void setSubscriptionEnable(boolean subscriptionEnable) {
		this.subscriptionEnable = subscriptionEnable;
	}
    
	public String getClientTimeZone() {
		return clientTimeZone;
	}

	public void setClientTimeZone(String clientTimeZone) {
		this.clientTimeZone = clientTimeZone;
	}
	public String getCIMProfileId() {
		return CIMProfileId;
	}

	public void setCIMProfileId(String cIMProfileId) {
		CIMProfileId = cIMProfileId;
	}

	private boolean digitalReceiptExtraction;
	
	
	public boolean isDigitalReceiptExtraction() {
		return digitalReceiptExtraction;
	}

	public void setDigitalReceiptExtraction(boolean digitalReceiptExtraction) {
		this.digitalReceiptExtraction = digitalReceiptExtraction;
	}

	//private Set<SecRoles> roles = new HashSet<SecRoles>();
	    	    
	   
	
		
	public String getUserDomainStr() {
		
		/*Set<UsersDomains> domainSet = userDomains;
		
		userDomainStr = "";
		
		for (UsersDomains usersDomains : domainSet) {
			
			 if(userDomainStr.length()>0) userDomainStr+=",";
			 userDomainStr += usersDomains.getDomainName();
				 
		}*/
		
		return userDomainStr;
	}

	public void setUserDomainStr(String userDomainStr) {
		this.userDomainStr = userDomainStr;
	}

	public String getUserRole() {
		return userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	

	public String getAccountType() {
		return accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	private UserOrganization userOrganization;
	
	public UserOrganization getUserOrganization() {
		return userOrganization;
	}

	public void setUserOrganization(UserOrganization userOrganization) {
		this.userOrganization = userOrganization;
	}

	private BigInteger userActivityAsBigInteger;
	

	private Users parentUser;

	private String loyaltyServiceType;

	

	public Users getParentUser() {
		return parentUser;
	}

	public void setParentUser(Users parentUser) {
		this.parentUser = parentUser;
	}

	public Users() {
    }

  
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getMqsId() {
        return this.mqsId;
    }
    
    public void setMqsId(String mqsId) {
        this.mqsId = mqsId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    public String getAddressOne() {
        return this.addressOne;
    }
    
    public void setAddressOne(String addressOne) {
        this.addressOne = addressOne;
    }
    public String getAddressTwo() {
        return this.addressTwo;
    }
    
    public void setAddressTwo(String addressTwo) {
        this.addressTwo = addressTwo;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPinCode() {
        return this.pinCode;
    }
    
    public void setPinCode(String pinCode) {
        this.pinCode = pinCode;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getVmta() {
		return vmta;
	}

	public void setVmta(String vmta) {
		this.vmta = vmta;
	}

	public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    
    public void setPackageStartDate(Calendar packageStartDate) {
		this.packageStartDate = packageStartDate;
	}

	public Calendar getPackageStartDate() {
		return packageStartDate;
	}

	public Calendar getPackageExpiryDate() {
        return this.packageExpiryDate;
    }
    
    public void setPackageExpiryDate(Calendar packageExpiryDate) {
    	this.packageExpiryDate = packageExpiryDate;
    }
    
    public void setEmailCount(Integer emailCount) {
    	this.emailCount = emailCount;
    }
    
    public Integer getEmailCount() {
    	return this.emailCount;
    }
    
    public void setUsedEmailCount(Integer usedEmailCount) {
    	this.usedEmailCount = usedEmailCount;
    }
    
    public Integer getUsedEmailCount() {
    	return this.usedEmailCount;
    }
    
    public Integer getSmsCount() {
		return smsCount;
	}

	public void setSmsCount(Integer smsCount) {
		this.smsCount = smsCount;
	}

	public Integer getUsedSmsCount() {
		return usedSmsCount;
	}

	public void setUsedSmsCount(Integer usedSmsCount) {
		this.usedSmsCount = usedSmsCount;
	}

    
	public String getUserActivitySettings() {
		return userActivitySettings;
	}

	public void setUserActivitySettings(String userActivitySettings) {
		
		this.userActivitySettings = userActivitySettings;
		
		if(this.userActivitySettings != null) {			
			this.userActivityAsBigInteger =  new BigInteger(this.userActivitySettings, 16);
		}
	}
	
	public Byte getFooterEditor() {
		return footerEditor;
	}

	public void setFooterEditor(Byte footerEditor) {
		this.footerEditor = footerEditor;
	}

	public BigInteger getActivityAsBigInteger() {
		return userActivityAsBigInteger;
	}
	
	
	public String getAddress() {
		StringBuffer address = new StringBuffer();
		if(this.getAddressOne() != null ) address.append("  " + this.getAddressOne());
		if(this.getAddressTwo() != null ) address.append("  " + this.getAddressTwo());
		if(this.getCity() != null ) address.append("  " + this.getCity());
		if(this.getState() != null ) address.append("  " + this.getState());
		if(this.getCountry() != null ) address.append("  " + this.getCountry());
		if(this.getPinCode() != null ) address.append("  " + this.getPinCode());
		return address.toString();
	}
	
	

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Override
	public int compareTo(Users user) {
		// TODO Auto-generated method stub
		return user.getUserName().compareTo(this.userName);
	}

	/*public boolean isTransactionalMsgChk() {
		return transactionalMsgChk;
	}

	public void setTransactionalMsgChk(boolean transactionalMsgChk) {
		this.transactionalMsgChk = transactionalMsgChk;
	}*/

	public String getUserSMSTool() {
		return userSMSTool;
	}

	public void setUserSMSTool(String userSMSTool) {
		this.userSMSTool = userSMSTool;
	}

	public Short getCountryCarrier() {
		return countryCarrier;
	}
	
	public void setCountryCarrier(Short countryCarrier) {
		this.countryCarrier = countryCarrier;
	}

	public String getMsgChkType() {
		return MsgChkType;
	}

	public void setMsgChkType(String msgChkType) {
		MsgChkType = msgChkType;
	}

	

	public BigInteger getUserActivityAsBigInteger() {
		return userActivityAsBigInteger;
	}

	public void setUserActivityAsBigInteger(BigInteger userActivityAsBigInteger) {
		this.userActivityAsBigInteger = userActivityAsBigInteger;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public boolean isEnableSMS() {
		return enableSMS;
	}

	public void setEnableSMS(boolean enableSMS) {
		this.enableSMS = enableSMS;
	}
	
	public Calendar getLastLoggedInTime() {
		return lastLoggedInTime;
	}

	public void setLastLoggedInTime(Calendar lastLoggedInTime) {
		this.lastLoggedInTime = lastLoggedInTime;
	}

	public String getLoyaltyServiceType() {
		return loyaltyServiceType;
	}

	public void setLoyaltyServiceType(String loyaltyServiceType) {
		this.loyaltyServiceType = loyaltyServiceType;
	}
	


	

	/*public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}
*/
	
	
	
	
	
	
	
	
	
	
}


