package org.mq.captiway.scheduler.beans;
// Generated 3 Aug, 2009 3:47:39 PM by Hibernate Tools 3.2.0.CR1



/**
 * ApplicationProperties generated by hbm2java
 */
@SuppressWarnings("serial")
public class ApplicationProperties  implements java.io.Serializable {


     private Long pId;
     private String key;
     private String value;

    public ApplicationProperties() {
    }

    public ApplicationProperties(String key, String value) {
       this.key = key;
       this.value = value;
    }
   
    public Long getpId() {
        return this.pId;
    }
    
    public void setpId(Long pId) {
        this.pId = pId;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


