package org.mq.captiway.scheduler.beans;
// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import org.mq.captiway.scheduler.utility.Constants;


/**
 * Campaigns generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class Campaigns implements java.io.Serializable {


     private Long campaignId;
     private String campaignName;
     private String label;
     private String subject;
     private String fromName;
     private String fromEmail;
     private String replyEmail;
     private String companyName;
     private Calendar createdDate;
     private Calendar modifiedDate;
     

     
     private String status;
     private String draftStatus;
     private String editorType;
     private String contentType;
     private String listsType;
     private String placeHoldersType;
     
     private String htmlText;
     private String finalHtmlText;
     private boolean prepared;
     private String textMessage;
     private boolean couponFlag;
     
     private String scheduleType;
     
     private boolean webLinkFlag;
     private String webLinkText;
     private String webLinkUrlText;
     private boolean permissionRemainderFlag;
     private String permissionRemainderText;
     
     
     private boolean addressFlag;
     private String addrsType;
     private Address address;
     private String addressStr;
     
     private short categoryWeight;
     private Set selectedDates = new HashSet(0);
     private Set<MailingList> mailingLists = new HashSet<MailingList>(0);
     private Users users;
     private SystemTemplates template;
     private boolean personalizeTo;
     private String toName;
     
   //Google Analytics settings
     private boolean googleAnalytics;
     private String googleAnalyticsCampTitle;
     
     private String includeBeforeStr;
     
  // susbcriber preference settings
     
     private Long categories;
     
   
	public Long getCategories() {
		return categories;
	}

	public void setCategories(Long categories) {
		this.categories = categories;
	}

     
     public String getIncludeBeforeStr() {
 		return includeBeforeStr;
 	}

 	public void setIncludeBeforeStr(String includeBeforeStr) {
 		this.includeBeforeStr = includeBeforeStr;
 	}
     
 	
 	private boolean includeOrg;
    private boolean includeOrgUnit;
    
   
    public boolean isIncludeOrg() {
   	 return includeOrg;
    }
    
    public void setIncludeOrg(boolean includeOrg) {
   	 this.includeOrg = includeOrg;
    }
    
    public boolean isIncludeOrgUnit() {
   	 return includeOrgUnit;
    }
    
    public void setIncludeOrgUnit(boolean includeOrgUnit) {
   	 this.includeOrgUnit = includeOrgUnit;
    }
    public String getAddrsType() {
		return addrsType;
	}

	public void setAddrsType(String addrsType) {
		this.addrsType = addrsType;
	}
     
    public Campaigns() {
    }

    public Long getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    public String getCampaignName() {
		return campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}


	public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public boolean isPersonalizeTo() {
		return personalizeTo;
	}


	public void setPersonalizeTo(boolean personalizeTo) {
		this.personalizeTo = personalizeTo;
	}


	public String getToName() {
		return toName;
	}


	public void setToName(String toName) {
		this.toName = toName;
	}


	public String getFromName() {
        return this.fromName;
    }
    
    public void setFromName(String fromName) {
        this.fromName = fromName;
    }
    public String getFromEmail() {
        return this.fromEmail;
    }
    
    public void setFromEmail(String fromEmail) {
        this.fromEmail = fromEmail;
    }
    public String getReplyEmail() {
        return this.replyEmail;
    }
    
    public void setReplyEmail(String replyEmail) {
        this.replyEmail = replyEmail;
    }
    public String getCompanyName() {
		return companyName;
	}


	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    
    public Calendar getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Calendar modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

	public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDraftStatus() {
		return draftStatus;
	}


	public void setDraftStatus(String draftStatus) {
		this.draftStatus = draftStatus;
	}


	public String getEditorType() {
        return this.editorType;
    }
    
    public void setEditorType(String editorType) {
        this.editorType = editorType;
    }
    public String getContentType() {
		return contentType;
	}


	public void setContentType(String contentType) {
		this.contentType = contentType;
	}


	public String getListsType() {
		return listsType;
	}


	public void setListsType(String listsType) {
		this.listsType = listsType;
	}


	public String getPlaceHoldersType() {
		return placeHoldersType;
	}


	public void setPlaceHoldersType(String placeHoldersType) {
		this.placeHoldersType = placeHoldersType;
	}


	public String getHtmlText() {
        return this.htmlText;
    }
    
    public void setHtmlText(String htmlText) {
        this.htmlText = htmlText;
    }
    public String getFinalHtmlText() {
        return this.finalHtmlText;
    }
    
    public void setFinalHtmlText(String finalHtmlText) {
        this.finalHtmlText = finalHtmlText;
    }

    public boolean isPrepared() {
		return prepared;
	}

	public void setPrepared(boolean prepared) {
		this.prepared = prepared;
	}


	public String getTextMessage() {
		return textMessage;
	}


	public void setTextMessage(String textMessage) {
		this.textMessage = textMessage;
	}


	public boolean isCouponFlag() {
        return this.couponFlag;
    }
    
    public void setCouponFlag(boolean couponFlag) {
        this.couponFlag = couponFlag;
    }
    public String getScheduleType() {
        return this.scheduleType;
    }
    
    public void setScheduleType(String scheduleType) {
        this.scheduleType = scheduleType;
    }
    public boolean isWebLinkFlag() {
        return this.webLinkFlag;
    }
    
    public void setWebLinkFlag(boolean webLinkFlag) {
        this.webLinkFlag = webLinkFlag;
    }
    public String getWebLinkText() {
        return this.webLinkText;
    }
    
    public void setWebLinkText(String webLinkText) {
        this.webLinkText = webLinkText;
    }
    public String getWebLinkUrlText() {
        return this.webLinkUrlText;
    }
    
    public void setWebLinkUrlText(String webLinkUrlText) {
        this.webLinkUrlText = webLinkUrlText;
    }
    public boolean isPermissionRemainderFlag() {
        return this.permissionRemainderFlag;
    }
    
    public void setPermissionRemainderFlag(boolean permissionRemainderFlag) {
        this.permissionRemainderFlag = permissionRemainderFlag;
    }
    public String getPermissionRemainderText() {
        return this.permissionRemainderText;
    }
    
    public void setPermissionRemainderText(String permissionRemainderText) {
        this.permissionRemainderText = permissionRemainderText;
    }
    public boolean isAddressFlag() {
        return this.addressFlag;
    }
    
    public void setAddressFlag(boolean addressFlag) {
        this.addressFlag = addressFlag;
    }
   
    public Set getSelectedDates() {
		return selectedDates;
	}


	public void setSelectedDates(Set selectedDates) {
		this.selectedDates = selectedDates;
	}


	public Set<MailingList> getMailingLists() {
        return this.mailingLists;
    }
    
    public void setMailingLists(Set<MailingList> mailingLists) {
        this.mailingLists = mailingLists;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public SystemTemplates getTemplate() {
        return this.template;
    }
    
    public void setTemplate(SystemTemplates template) {
        this.template = template;
    }


	public short getCategoryWeight() {
		return categoryWeight;
	}

	public void setCategoryWeight(short categoryWeight) {
		this.categoryWeight = categoryWeight;
	}
	
	
	public boolean isGoogleAnalytics() {
		return googleAnalytics;
	}

	public void setGoogleAnalytics(boolean googleAnalytics) {
		this.googleAnalytics = googleAnalytics;
	}

	public String getGoogleAnalyticsCampTitle() {
		return googleAnalyticsCampTitle;
	}

	public void setGoogleAnalyticsCampTitle(String googleAnalyticsCampTitle) {
		this.googleAnalyticsCampTitle = googleAnalyticsCampTitle;
	}


	private String listNames ;
	
	public String getListNames() {
		
		listNames = "";
		for(MailingList ml : mailingLists) {
			
			if(listNames.length() > 0) {
				listNames +=","+ml.getListName();
			}else {
				listNames += ml.getListName();
			}
		}
		return listNames;
	}


	public Address getAddress() {
		
		if(address == null) {
			address = new Address();
			try {
				
				if(addressStr == null)	return address;
				
				if(addressStr.startsWith("|^") && addressStr.endsWith("^|")) {
					
					address.setDinamicAddrstr(addressStr);
					
				}
				else {
					String[] addrArr = addressStr.split(Constants.ADDR_COL_DELIMETER);
					
					address.setAddressOne((addrArr[0]== null)?"":addrArr[0]);
					address.setAddressTwo((addrArr[1]== null)?"":addrArr[1]);
					address.setCity((addrArr[2]== null)?"":addrArr[2]);
					address.setState((addrArr[3] == null)?"":addrArr[3]);
					address.setCountry((addrArr[4] == null)?"":addrArr[4]);
					
					if(addrArr.length > 5 && addrArr[5] != null) {
						address.setPin(addrArr[5]);
//						address.setPin(Long.parseLong(addrArr[5]));
					}
					
					if(addrArr.length > 6 ) {
						address.setPhone((addrArr[6] == null)?"":addrArr[6]);
					}
				
				}
			} catch (NumberFormatException e) {
				
			} catch (ArrayIndexOutOfBoundsException iob) {
				
			} catch (Exception ex) {
				
			}
		}
		return address;
	}


	public void setAddress(Address address) {
		this.address = address;
		StringBuffer sb = new StringBuffer();
		if(address.getDinamicAddrstr() != null) {
			sb.append(address.getDinamicAddrstr());
			this.addressStr = sb.toString();
		}else {
			sb.append(((address.getAddressOne() == null)?"": address.getAddressOne()));
			sb.append(Constants.ADDR_COL_DELIMETER+((address.getAddressTwo() == null) ?"":address.getAddressTwo()));
			sb.append(Constants.ADDR_COL_DELIMETER+((address.getCity() == null)?"":address.getCity()));
			sb.append(Constants.ADDR_COL_DELIMETER+((address.getState() == null)?"":address.getState()));
			sb.append(Constants.ADDR_COL_DELIMETER+((address.getCountry() == null)?"":address.getCountry()));
			sb.append(Constants.ADDR_COL_DELIMETER+((address.getPin() == null)?"":address.getPin()));
			sb.append(Constants.ADDR_COL_DELIMETER+((address.getPhone() == null)?"":address.getPhone()));
			this.addressStr = sb.toString();
		}
	}


	public String getAddressStr() {
		return addressStr;
	}


	public void setAddressStr(String addressStr) {
		this.addressStr = addressStr;
	}
	
}


