package org.mq.captiway.scheduler.beans;
// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;

/**
 * Messages generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class Messages  implements java.io.Serializable {


     private Long id;
     private String module;
     private String subject;
     private String message;
     private Calendar createdDate;
     private String folder;
     private boolean read;
     private String type;
     private Users users;

    public Messages() {
    }

	
    public Messages(String module, String subject, String message, Users users) {
        this.module = module;
        this.subject = subject;
        this.message = message;
        this.users = users;
    }
    
    public Messages(String module, String subject, String message, Calendar createdDate, 
    		String folder, Boolean read, String type, Users users) {
    	
       this.module = module;
       this.subject = subject;
       this.message = message;
       this.createdDate = createdDate;
       this.folder = folder;
       this.read = read;
       this.type = type;
       this.users = users;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    public String getFolder() {
        return this.folder;
    }
    
    public void setFolder(String folder) {
        this.folder = folder;
    }

    public boolean isRead() {
		return read;
	}

	public void setRead(boolean read) {
		this.read = read;
	}

	public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


