package org.mq.captiway.scheduler.beans;
// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1



/**
 * CampaignSent generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class CampaignSent  implements java.io.Serializable {


     private Long sentId;
     private String emailId;
     private CampaignReport campaignReport;
     private String status;
     private int opens;
     private int clicks;
     private Long contactId;
     private Long campaignId;
     
     private String contactPhValStr;
     
 	

	public Long getCampaignId() {
		return campaignId;
	}


	public void setCampaignId(Long campaignId) {
		this.campaignId = campaignId;
	}

	public CampaignSent() {
    }

	
    /*public CampaignSent(Long sentId, String emailId, CampaignReport campaignReport, String status) {
        this.sentId = sentId;
    	this.emailId = emailId;
        this.campaignReport = campaignReport;
        this.status = status;
    }*/
    
    public CampaignSent(Long sentId, String emailId, CampaignReport campaignReport, String status, Long contactId, Long campaignId) {
        this.sentId = sentId;
    	this.emailId = emailId;
        this.campaignReport = campaignReport;
        this.status = status;
        this.contactId = contactId;
        this.campaignId = campaignId;
    }
        
    public Long getSentId() {
        return this.sentId;
    }
    
    public void setSentId(Long sentId) {
        this.sentId = sentId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public CampaignReport getCampaignReport() {
        return this.campaignReport;
    }
    
    public void setCampaignReport(CampaignReport campaignReport) {
        this.campaignReport = campaignReport;
    }

	public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public int getOpens() {
        return this.opens;
    }
    
    public void setOpens(int opens) {
        this.opens = opens;
    }
    public int getClicks() {
        return this.clicks;
    }
    
    public void setClicks(int clicks) {
        this.clicks = clicks;
    }


	public Long getContactId() {
		return contactId;
	}


	public void setContactId(Long contactId) {
		this.contactId = contactId;
	}
	
	public String getContactPhValStr() {
		return contactPhValStr;
	}


	public void setContactPhValStr(String contactPhValStr) {
		this.contactPhValStr = contactPhValStr;
	}


}


