package org.mq.captiway.scheduler.beans;
// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * Clicks generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class Clicks  implements java.io.Serializable {


     private Long clickId;
     private CampaignSent sentId;
     private String clickUrl;
     private Date clickDate;

    public Clicks() {
    }

	
    public Clicks(CampaignSent sentId) {
        this.sentId = sentId;
    }
    public Clicks(CampaignSent sentId, String clickUrl, Date clickDate) {
       this.sentId = sentId;
       this.clickUrl = clickUrl;
       this.clickDate = clickDate;
    }
   
    public Long getClickId() {
        return this.clickId;
    }
    
    public void setClickId(Long clickId) {
        this.clickId = clickId;
    }
    public CampaignSent getSentId() {
        return this.sentId;
    }
    
    public void setSentId(CampaignSent sentId) {
        this.sentId = sentId;
    }
    public String getClickUrl() {
        return this.clickUrl;
    }
    
    public void setClickUrl(String clickUrl) {
        this.clickUrl = clickUrl;
    }
    public Date getClickDate() {
        return this.clickDate;
    }
    
    public void setClickDate(Date clickDate) {
        this.clickDate = clickDate;
    }




}


