package org.mq.captiway.scheduler.beans;
// Generated Nov 17, 2008 10:20:05 AM by Hibernate Tools 3.2.0.CR1


import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import org.mq.captiway.scheduler.beans.MailingList;
import org.mq.captiway.scheduler.beans.Users;

/**
 * Contacts generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class Contacts  implements java.io.Serializable {


     private Long contactId;
     //private MailingList mailingList;
     //private Set<MailingList> mlSet = new HashSet<MailingList>(0);
     private Users users;
     
     private String emailId;
     private String firstName;
     private String lastName;
     private Calendar createdDate;
     private Boolean purged = false;
     private Boolean optinStatus;
     private String emailStatus;
     private Date lastStatusChange;
     private Date lastMailDate;
     private String addressOne;
     private String addressTwo;
     private String city;
     private String state;
     private String country;
     private int pin;
     private Long phone;
     private Byte optin;
     private String subscriptionType;
     private String mobileStatus;
     
     private Object tempObj;
     private String phValueStr;
     
     private String externalId;
     private String optinMedium;
     private String gender;
     private Calendar birthDay;
     private Calendar anniversary;
     private String homeStore;
     private String subsidiaryNumber;
     private Boolean pushNotification=true;
     private String instanceId;
     private String deviceType;

 	public String getSubsidiaryNumber() {
 		return subsidiaryNumber;
 	}

 	public void setSubsidiaryNumber(String subsidiaryNumber) {
 		this.subsidiaryNumber = subsidiaryNumber;
 	}

     private Byte optedInto;
     private Byte optinPerType;
     
     
     private String udf1;
     private String udf2;
     private String udf3;
     private String udf4;
     private String udf5;
     private String udf6;
     private String udf7;
     private String udf8;
     private String udf9;
     private String udf10;
     private String udf11;
     private String udf12;
     private String udf13;
     private String udf14;
     private String udf15;
     
     private Long hpId;
     private Byte loyaltyCustomer;
     
     
     private String zip;
     private String mobilePhone;
     private String homePhone; 

     private Calendar lastSMSDate;
     private Calendar lastWADate;
	private boolean mobileOptin;

	private Long mlBits;
	
	private String categories;
	private int lastMailSpan;
	private int lastSmsSpan;
     
//     private CustomFieldData custFieldData;
	private Calendar mobileOptinDate;
	private String mobileOptinSource;
	
	private Calendar lastNotificationDate;
	
	public Calendar getMobileOptinDate() {
		return mobileOptinDate;
	}

	public void setMobileOptinDate(Calendar mobileOptinDate) {
		this.mobileOptinDate = mobileOptinDate;
	}

	public String getMobileOptinSource() {
		return mobileOptinSource;
	}

	public void setMobileOptinSource(String mobileOptinSource) {
		this.mobileOptinSource = mobileOptinSource;
	}
     
    public Contacts() {
    }
    
    public Contacts(Contacts contact) {
        //this.mailingList = contact.getMailingList();
    	//this.mlSet = contact.getMlSet();
    	this.mlBits = contact.getMlBits();
        this.emailId = contact.getEmailId();
        this.firstName = contact.getFirstName();
        this.lastName = contact.getLastName();
        this.createdDate = Calendar.getInstance();
        this.optinStatus = contact.getOptinStatus();
        this.emailStatus = contact.getEmailStatus();
        this.addressOne = contact.getAddressOne();
        this.addressTwo = contact.getAddressTwo();
        this.city = contact.getCity();
        this.state = contact.getState();
        this.country = contact.getCountry();
       /* this.pin = contact.getPin();
        this.phone = contact.getPhone();*/
        this.optin = contact.getOptin();
        this.subscriptionType = contact.getSubscriptionType();
        this.zip = contact.getZip();
        this.mobilePhone = contact.getMobilePhone();
    }
	
    public Contacts(MailingList mailingList, String emailId, String emailStatus) {
        //this.mailingList = mailingList;
    	//this.mlSet.add(mailingList);
    	this.mlBits = mailingList.getMlBit();
        this.emailId = emailId;
        this.emailStatus = emailStatus;
    }
    
	public Contacts(MailingList mailingList, Calendar createdDate, Boolean optinStatus, String emailStatus) {
       //this.mailingList = mailingList;
		//this.mlSet.add(mailingList);
	   this.mlBits = mailingList.getMlBit();
       this.createdDate = createdDate;
       this.optinStatus = optinStatus;
       this.emailStatus = emailStatus;
    }

	public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, Calendar createdDate, Boolean optinStatus, String emailStatus, Date lastStatusChange) {
       //this.mailingList = mailingList;
		//this.mlSet.add(mailingList);
	   this.mlBits = mailingList.getMlBit();
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.optinStatus = optinStatus;
       this.emailStatus = emailStatus;
       this.lastStatusChange = lastStatusChange;
    }

     /* public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, Date createdDate, Boolean optinStatus, String emailStatus, Date lastStatusChange,Date lastMailDate, String addressOne, String addressTwo, String city, 
    					String state, String country, int pin, Long phone,byte optin,String subscriptionType, String zip,String mobilePhone) {*/
	 public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, Calendar createdDate, Boolean optinStatus, String emailStatus, Date lastStatusChange,Date lastMailDate, String addressOne, String addressTwo, String city, 
				String state, String country, byte optin,String subscriptionType, String zip,String mobilePhone) {
       //this.mailingList = mailingList;
    	//this.mlSet.add(mailingList);
	   this.mlBits = mailingList.getMlBit();
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.optinStatus = optinStatus;
       this.emailStatus = emailStatus;
       this.lastStatusChange = lastStatusChange;
       this.lastMailDate = lastMailDate;
       this.addressOne = addressOne;
       this.addressTwo = addressTwo;
       this.city = city;
       this.state = state;
       this.country = country;
       /*this.pin = pin;
       this.phone = phone;*/
       this.optin = optin;
       this.subscriptionType = subscriptionType;
       this.zip = zip;
       this.mobilePhone = mobilePhone;
    }
    /* public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, Date createdDate, Boolean optinStatus, String emailStatus, String addressOne, String addressTwo, 
    		String city, String state, String country, int pin, Long phone,String zip,String mobilePhone) {*/
	 public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, Calendar createdDate, Boolean optinStatus, String emailStatus, String addressOne, String addressTwo, 
	    		String city, String state, String country, String zip,String mobilePhone) {
    	
    	//this.mlSet.add(mailingList);
	   this.mlBits = mailingList.getMlBit();
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.optinStatus = optinStatus;
       this.emailStatus = emailStatus;
       this.addressOne = addressOne;
       this.addressTwo = addressTwo;
       this.city = city;
       this.state = state;
       this.country = country;
       /*this.pin = pin;
       this.phone = phone;*/
       this.zip = zip;
       this.mobilePhone = mobilePhone;
    }
   
     /* public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, Date createdDate, Boolean optinStatus, 
    		String emailStatus, Date lastStatusChange, String addressOne, String addressTwo, String city, String state, 
    		String country, int pin, Long phone,String zip,String mobilePhone) {*/
	 public Contacts(MailingList mailingList, String emailId, String firstName, String lastName, Calendar createdDate, Boolean optinStatus, 
	    		String emailStatus, Date lastStatusChange, String addressOne, String addressTwo, String city, String state, 
	    		String country, String zip,String mobilePhone) {
       //this.mailingList = mailingList;
    	//this.mlSet.add(mailingList);
	   this.mlBits = mailingList.getMlBit();
       this.emailId = emailId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.optinStatus = optinStatus;
       this.emailStatus = emailStatus;
       this.lastStatusChange = lastStatusChange;
       this.addressOne = addressOne;
       this.addressTwo = addressTwo;
       this.city = city;
       this.state = state;
       this.country = country;
      /* this.pin = pin;
       this.phone = phone;*/
       this.zip = zip;
       this.mobilePhone = mobilePhone;
    }
   /*public Contacts(Long contactId,MailingList mailingList, String emailId, String firstName, String lastName, 
    		Date createdDate, Boolean purged, Boolean optinStatus, String emailStatus, Date lastStatusChange,Date lastMailDate, 
    		String addressOne, String addressTwo, String city, String state, String country, 
    		int pin, Long phone,byte optin,String subscriptionType, String zip,String mobilePhone) {*/
	 public Contacts(Long contactId,MailingList mailingList, String emailId, String firstName, String lastName, 
			 Calendar createdDate, Boolean purged, Boolean optinStatus, String emailStatus, Date lastStatusChange,Date lastMailDate, 
	    		String addressOne, String addressTwo, String city, String state, String country, 
	    		byte optin,String subscriptionType, String zip,String mobilePhone) {
    	//added for EventTrigger
    	this.contactId = contactId; 
    	//this.mailingList = mailingList;
    	//this.mlSet.add(mailingList);
    	this.mlBits = mailingList.getMlBit();
        this.emailId = emailId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.createdDate = createdDate;
        this.purged = purged;
        this.optinStatus = optinStatus;
        this.emailStatus = emailStatus;
        this.lastStatusChange = lastStatusChange;
        this.lastMailDate = lastMailDate;
        this.addressOne = addressOne;
        this.addressTwo = addressTwo;
        this.city = city;
        this.state = state;
        this.country = country;
        /*this.pin = pin;
        this.phone = phone;*/
        this.optin = optin;
        this.subscriptionType = subscriptionType;
        this.zip = zip;
        this.mobilePhone = mobilePhone;
        
     }
  
    public Contacts(MailingList mailingList, Calendar createdDate, String emailStatus) {
        //this.mailingList = mailingList;
    	//this.mlSet.add(mailingList);
    	this.mlBits = mailingList.getMlBit();
        this.createdDate = createdDate;
        this.emailStatus = emailStatus;
     }
    
    
    
    
    public Long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }
    /*public MailingList getMailingList() {
        return this.mailingList;
    }
    
    public void setMailingList(MailingList mailingList) {
        this.mailingList = mailingList;
    }*/
    
    /*public MailingList getMailingListByType(String listType) {
        
    	if(this.mlSet == null || this.mlSet.isEmpty()) return null;
    	
    	Iterator<MailingList> listIt = this.mlSet.iterator();
    	MailingList tempList = null;
    	while(listIt.hasNext()){
    		tempList = listIt.next();
    		if(tempList.getListType().equals(listType)) return tempList;
    	}
    	return null;
    }//getMailingListByType
*/    
   /* public Set<MailingList> getMlSet() {
		return mlSet;
	}

	public void setMlSet(Set<MailingList> mlSet) {
		this.mlSet = mlSet;
	}*/

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
    
    public String getEmailId() {
        return this.emailId;
    }
    
	public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Calendar getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Calendar createdDate) {
        this.createdDate = createdDate;
    }
    
    public Boolean getPurged() {
		return purged;
	}

	public void setPurged(Boolean purged) {
		this.purged = purged;
	}

	public Boolean getOptinStatus() {
        return this.optinStatus;
    }
    
    public void setOptinStatus(Boolean optinStatus) {
        this.optinStatus = optinStatus;
    }
    public String getEmailStatus() {
        return this.emailStatus;
    }
    
    public void setEmailStatus(String emailStatus) {
        this.emailStatus = emailStatus;
    }
    public Date getLastMailDate() {
        return this.lastMailDate;
    }
    
    public void setLastMailDate(Date lastMailDate) {
        this.lastMailDate = lastMailDate;
    }

    public Date getLastStatusChange() {
        return this.lastStatusChange;
    }
    
    public void setLastStatusChange(Date lastStatusChange) {
        this.lastStatusChange = lastStatusChange;
    }
    public String getAddressOne() {
        return this.addressOne;
    }
    
    public void setAddressOne(String addressOne) {
        this.addressOne = addressOne;
    }
    public String getAddressTwo() {
        return this.addressTwo;
    }
    
    public void setAddressTwo(String addressTwo) {
        this.addressTwo = addressTwo;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public int getPin() {
        return this.pin;
    }
    
    public void setPin(int pin) {
        this.pin = pin;
    }
    public Long getPhone() {
        return this.phone;
    }
    
    public void setPhone(Long phone) {
        this.phone = phone;
    }

	public Byte getOptin() {
		if(this.optin == null) 
			this.optin = Byte.valueOf((byte)(0));
		return optin;
	}

	public void setOptin(Byte optin) {
		this.optin = optin;
	}

	public String getSubscriptionType() {
		return subscriptionType;
	}

	public void setSubscriptionType(String subscriptionType) {
		this.subscriptionType = subscriptionType;
	}

	public Object getTempObj() {
		return tempObj;
	}

	public void setTempObj(Object tempObj) {
		this.tempObj = tempObj;
	}
	
	public String getPhValueStr() {
		return phValueStr;
	}

	public void setPhValueStr(String phValueStr) {
		this.phValueStr = phValueStr;
	}

	public String getExternalId() {
		return externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getOptinMedium() {
		return optinMedium;
	}

	public void setOptinMedium(String optinMedium) {
		this.optinMedium = optinMedium;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Calendar getBirthDay() {
		return birthDay;
	}

	public void setBirthDay(Calendar birthDay) {
		this.birthDay = birthDay;
	}

	public Calendar getAnniversary() {
		return anniversary;
	}

	public void setAnniversary(Calendar anniversary) {
		this.anniversary = anniversary;
	}

	

	public String getHomeStore() {
		return homeStore;
	}

	public void setHomeStore(String homeStore) {
		this.homeStore = homeStore;
	}

	public Byte getOptedInto() {
		return optedInto;
	}

	public void setOptedInto(Byte optedInto) {
		this.optedInto = optedInto;
	}

	public Byte getOptinPerType() {
		return optinPerType;
	}

	public void setOptinPerType(Byte optinPerType) {
		this.optinPerType = optinPerType;
	}

	public String getUdf1() {
		return udf1;
	}

	public void setUdf1(String udf1) {
		this.udf1 = udf1;
	}

	public String getUdf2() {
		return udf2;
	}

	public void setUdf2(String udf2) {
		this.udf2 = udf2;
	}

	public String getUdf3() {
		return udf3;
	}

	public void setUdf3(String udf3) {
		this.udf3 = udf3;
	}

	public String getUdf4() {
		return udf4;
	}

	public void setUdf4(String udf4) {
		this.udf4 = udf4;
	}

	public String getUdf5() {
		return udf5;
	}

	public void setUdf5(String udf5) {
		this.udf5 = udf5;
	}

	public String getUdf6() {
		return udf6;
	}

	public void setUdf6(String udf6) {
		this.udf6 = udf6;
	}

	public String getUdf7() {
		return udf7;
	}

	public void setUdf7(String udf7) {
		this.udf7 = udf7;
	}

	public String getUdf8() {
		return udf8;
	}

	public void setUdf8(String udf8) {
		this.udf8 = udf8;
	}

	public String getUdf9() {
		return udf9;
	}

	public void setUdf9(String udf9) {
		this.udf9 = udf9;
	}

	public String getUdf10() {
		return udf10;
	}

	public void setUdf10(String udf10) {
		this.udf10 = udf10;
	}

	public String getUdf11() {
		return udf11;
	}

	public void setUdf11(String udf11) {
		this.udf11 = udf11;
	}

	public String getUdf12() {
		return udf12;
	}

	public void setUdf12(String udf12) {
		this.udf12 = udf12;
	}

	public String getUdf13() {
		return udf13;
	}

	public void setUdf13(String udf13) {
		this.udf13 = udf13;
	}

	public String getUdf14() {
		return udf14;
	}

	public void setUdf14(String udf14) {
		this.udf14 = udf14;
	}

	public String getUdf15() {
		return udf15;
	}

	public void setUdf15(String udf15) {
		this.udf15 = udf15;
	}

	public Long getHpId() {
		return hpId;
	}

	public void setHpId(Long hpId) {
		this.hpId = hpId;
	}

	public Byte getLoyaltyCustomer() {
		return loyaltyCustomer;
	}

	public void setLoyaltyCustomer(Byte loyaltyCustomer) {
		this.loyaltyCustomer = loyaltyCustomer;
	}

	public String toString() {
		return this.emailId;
	}

	public String getMobileStatus() {
		return mobileStatus;
	}

	public void setMobileStatus(String mobileStatus) {
		this.mobileStatus = mobileStatus;
	}
	
	
	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getHomePhone() {
		return homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}
	
	public Calendar getLastSMSDate() {
		return lastSMSDate;
	}

	public void setLastSMSDate(Calendar lastSMSDate) {
		this.lastSMSDate = lastSMSDate;
	}

	public Calendar getLastWADate() {
		return lastWADate;
	}

	public void setLastWADate(Calendar lastWADate) {
		this.lastWADate = lastWADate;
	}

	public boolean isMobileOptin() {
		return mobileOptin;
	}

	public void setMobileOptin(boolean mobileOptin) {
		this.mobileOptin = mobileOptin;
	}

	public Long getMlBits() {
		return mlBits;
	}

	public void setMlBits(Long mlBits) {
		this.mlBits = mlBits;
	}
	
	public String getCategories() {
		return categories;
	}

	public void setCategories(String categories) {
		this.categories = categories;
	}

	public int getLastMailSpan() {
		return lastMailSpan;
	}

	public void setLastMailSpan(int lastMailSpan) {
		this.lastMailSpan = lastMailSpan;
	}

	public int getLastSmsSpan() {
		return lastSmsSpan;
	}

	public void setLastSmsSpan(int lastSmsSpan) {
		this.lastSmsSpan = lastSmsSpan;
	}

	public Calendar getLastNotificationDate() {
		return lastNotificationDate;
	}

	public void setLastNotificationDate(Calendar lastNotificationDate) {
		this.lastNotificationDate = lastNotificationDate;
	}

	public Boolean getPushNotification() {
		return pushNotification;
	}

	public void setPushNotification(Boolean pushNotification) {
		this.pushNotification = pushNotification;
	}

	public String getInstanceId() {
		return instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

	public String getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}
	
	private Calendar modifiedDate;
    public Calendar getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Calendar modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
}
