package org.mq.captiway.scheduler.beans;
// Generated 30 Nov, 2009 6:24:52 PM by Hibernate Tools 3.2.0.CR1

/**
 * EmailClient generated by hbm2java
 */
public class EmailClient  implements java.io.Serializable {


     private Long emailClientId;
     private String emailClient;
     private String userAgent;

    public EmailClient() {
    }

    public EmailClient(String emailClient) {
       this.emailClient = emailClient;
    }
   
    public Long getEmailClientId() {
        return this.emailClientId;
    }
    
    public void setEmailClientId(Long emailClientId) {
        this.emailClientId = emailClientId;
    }
    public String getEmailClient() {
        return this.emailClient;
    }
    
    public void setEmailClient(String emailClient) {
        this.emailClient = emailClient;
    }

	public String getUserAgent() {
		return userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}
}


