package org.mq.captiway.scheduler.beans;

import java.util.Calendar;
import java.util.Date;


// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1



/**
 * Campaigns generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class EmailQueue  implements java.io.Serializable {


    private long id; 
	//private Campaigns campaign;
    private Long campaignId;
    public Long getCampaignId() {
		return campaignId;
	}

	public void setCampaignId(Long campaignId) {
		this.campaignId = campaignId;
	}
    private String type;
    private String status;
    private String toEmailId;
    private String message;
    private String subject;
    private Date sentDate;
    private Users user;
    //private CustomTemplates customTemplates;

	private String childEmail;
    private String childFirstName;
    private String dateOfBirth;
    
    private Long contactId; 
    
    private String ccEmailId;
    private Long loyaltyId;
	private String bccEmailId;
	private String deliveryStatus;
	private int opens;
	private int clicks; 
	private String custTempName;
    
    public String getCcEmailId() {
		return ccEmailId;
	}

	public void setCcEmailId(String ccEmailId) {
		this.ccEmailId = ccEmailId;
	}

	/*public CustomTemplates getCustomTemplates() {
		return customTemplates;
	}

	public void setCustomTemplates(CustomTemplates customTemplates) {
		this.customTemplates = customTemplates;
	}*/

	public EmailQueue(){
    }
	
    public EmailQueue(String subject,String message, String type, String status,String toEmailId,Date sentDate,Users user) {
    	this.subject = subject;
    	this.message = message;
    	this.type = type;
        this.status = status;
        this.toEmailId = toEmailId;
        this.sentDate = sentDate;
        this.user = user;
    }
    
    public EmailQueue(String subject,String message, String type, String status,String toEmailId,String ccEmailId,Date sentDate,Users user) {
    	this.subject = subject;
    	this.message = message;
    	this.type = type;
        this.status = status;
        this.toEmailId = toEmailId;
        this.ccEmailId = ccEmailId;
        this.sentDate = sentDate;
        this.user = user;
    }
    
    public EmailQueue(Long campaignId, String type, String status, String toEmailId,Date sentDate,Users user) {
    	this.campaignId = campaignId;
    	this.type = type;
        this.status = status;
        this.toEmailId = toEmailId;
        this.sentDate = sentDate;
        this.user = user;
    }
    
    
  public EmailQueue(Long campaignId, Long customTemplateId, String type, String status, String toEmailId,Users user) {
    	
	  this.campaignId = campaignId;
	  	this.customTemplateId = customTemplateId;
    	this.type = type;
        this.status = status;
        this.toEmailId = toEmailId;
        
        this.user = user;
    }
   
  public EmailQueue(Long campaignId, Long customTemplateId, String type,
		  String status, String toEmailId,Users user, String childEmail, String childFirstName, String dateOfBirth) {
  	
  	this.campaignId = campaignId;
  	this.customTemplateId = customTemplateId;
  	this.type = type;
  	this.status = status;
  	this.toEmailId = toEmailId;
  	this.user = user;
  	this.childEmail = childEmail;
  	this.dateOfBirth = dateOfBirth;
  	this.childFirstName = childFirstName;
  	
  }
  
  
  public EmailQueue(Long customTemplateId, String type, String message,
  		  String status, String toEmailId,Users user,Date sentDate, String subject, String childEmail, String childFirstName, String dateOfBirth, Long contactId) {
    	this.subject = subject;
    	this.message = message;
    	this.customTemplateId = customTemplateId;
    	this.type = type;
    	this.status = status;
    	this.toEmailId = toEmailId;
    	this.user = user;
    	this.sentDate = sentDate;
    	this.childEmail = childEmail;
    	this.dateOfBirth = dateOfBirth;
    	this.childFirstName = childFirstName;
    	this.contactId = contactId;
    	
    }
    
  
  public EmailQueue(String subject,String message, String type, String status,String toEmailId,Date sentDate) {
	  this.subject = subject;
	  this.message = message;
	  this.type = type;
	  this.status = status;
	  this.toEmailId = toEmailId;
	  this.sentDate = sentDate;
  }
  
  public EmailQueue(Long customTemplateId, String type, String message,
			String status, String toEmailId,Users user,Date sentDate, String subject, Long contactId,Long loyaltyId) {
	  this.customTemplateId = customTemplateId;
		this.subject = subject;
		this.message = message;
		this.type = type;
		this.status = status;
		this.toEmailId = toEmailId;
		this.sentDate = sentDate;
		this.user = user;
		this.contactId = contactId;
		this.loyaltyId = loyaltyId;
	}
  
    public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/*public void setCampaign(Campaigns campaign) {
		this.campaign = campaign;
	}

	public Campaigns getCampaign() {
        return this.campaign;
    }
    */
    public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getToEmailId() {
        return this.toEmailId;
    }
    
    public void setToEmailId(String toEmailId) {
        this.toEmailId = toEmailId;
    }

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getSentDate() {
		return sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}
	
	 public String getChildEmail() {
		return childEmail;
	}

	public void setChildEmail(String childEmail) {
		this.childEmail = childEmail;
	}

	public String getChildFirstName() {
		return childFirstName;
	}

	public void setChildFirstName(String childFirstname) {
		this.childFirstName = childFirstname;
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	
	
	public Long getContactId() {
		return contactId;
	}

	public void setContactId(Long contactId) {
		this.contactId = contactId;
	}

	public Long getLoyaltyId() {
		return loyaltyId;
	}

	public void setLoyaltyId(Long loyaltyId) {
		this.loyaltyId = loyaltyId;
	}
	
		public String getBccEmailId() {
		return bccEmailId;
	}

	public void setBccEmailId(String bccEmailId) {
		this.bccEmailId = bccEmailId;
	}

	public String getDeliveryStatus() {
		return deliveryStatus;
	}

	public void setDeliveryStatus(String deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	public int getOpens() {
		return opens;
	}

	public void setOpens(int opens) {
		this.opens = opens;
	}

	public int getClicks() {
		return clicks;
	}

	public void setClicks(int clicks) {
		this.clicks = clicks;
	}

	public String getCustTempName() {
		return custTempName;
	}

	public void setCustTempName(String custTempName) {
		this.custTempName = custTempName;
	}
private Long customTemplateId;
    
    public Long getCustomTemplateId() {
		return customTemplateId;
	}

	public void setCustomTemplateId(Long customTemplateId) {
		this.customTemplateId = customTemplateId;
	}
	

}


