package org.mq.captiway.scheduler.beans;
// Generated Nov 25, 2008 11:19:15 AM by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.mq.captiway.scheduler.beans.EventTrigger;

/**
 * MailingList generated by hbm2java
 */
@SuppressWarnings({ "unchecked", "serial" })
public class MailingList  implements java.io.Serializable, Comparable {

	 private Long listId;
     private String listName;
     private String description;
     private Date createdDate;
     private String status;
     private Date lastStatusChangeDate;
     private Date lastModifiedDate;
     private boolean custField;
     private boolean consent;
     private Set campaigns = new HashSet(0);
     private Users users;
     private Long size;
     private Long custTemplateId;
     private Boolean checkDoubleOptin;
     private Set<EventTrigger> triggersSet;
     private Set<EventTrigger> triggerSetToBeAddedToMls;
     private Long listSize;
     
     public Long getListSize() {
		return listSize;
	}
	public void setListSize(Long listSize) {
		this.listSize = listSize;
	}
	private boolean checkParentalConsent;
     private boolean checkLoyaltyOptin;
     
     public boolean isCheckLoyaltyOptin() {
		return checkLoyaltyOptin;
	}
	public void setCheckLoyaltyOptin(boolean checkLoyaltyOptin) {
		this.checkLoyaltyOptin = checkLoyaltyOptin;
	}
	public boolean isCheckParentalConsent() {
		return checkParentalConsent;
     }
	public void setCheckParentalConsent(boolean checkParentalConsent) {
		this.checkParentalConsent = checkParentalConsent;
	}
	private Long loyaltyCutomTempId;
	public Long getLoyaltyCutomTempId() {
		return loyaltyCutomTempId;
	}
	public void setLoyaltyCutomTempId(Long loyaltyCutomTempId) {
		this.loyaltyCutomTempId = loyaltyCutomTempId;
	}
	private Long consentCutomTempId;
	public Long getConsentCutomTempId() {
		return consentCutomTempId;
	}
	
	public void setConsentCutomTempId(Long consentCutomTempId) {
		this.consentCutomTempId = consentCutomTempId;
	}

	 private boolean checkWelcomeMsg;
     private Long welcomeCustTempId;
     
     public Long getWelcomeCustTempId() {
    	 return welcomeCustTempId;
     }
     
     public void setWelcomeCustTempId(Long welcomeCustTempId) {
    	 this.welcomeCustTempId = welcomeCustTempId;
     }
     
     public boolean isCheckWelcomeMsg() {
		return checkWelcomeMsg;
	}

	public void setCheckWelcomeMsg(boolean checkWelcomeMsg) {
		this.checkWelcomeMsg = checkWelcomeMsg;
	}

     
     private String listType;
     private Long mlBit;
     
     
   //added for sharing
	 private Set<UsersDomains> sharedToDomain = new HashSet<UsersDomains>(0);
	
	 public Set<UsersDomains> getSharedToDomain() {
		return sharedToDomain;
	 }
	
	 public void setSharedToDomain(Set<UsersDomains> sharedToDomain) {
		this.sharedToDomain = sharedToDomain;
	 }
     
     
     
    public MailingList() {
    }
    public MailingList(MailingList mlist){
        this.listName = mlist.getListName();
        this.description = mlist.getDescription();
        this.createdDate = new Date();
        this.status = mlist.getStatus();
        this.users = mlist.getUsers();
    }
	
    public MailingList(String listName, boolean consent,Users users) {
        this.listName = listName;
        this.users = users;
        this.consent = consent;
    }
    public MailingList(String listName, String description, Date createdDate,
    		String status, Date lastStatusChangeDate, Date lastModifiedDate,
    		boolean consent, boolean custField, Set campaigns, Users users,
    		Boolean checkDoubleOptin,Long custTemplateId) {
       this.listName = listName;
       this.description = description;
       this.createdDate = createdDate;
       this.status = status;
       this.lastStatusChangeDate = lastStatusChangeDate;
       this.lastModifiedDate = lastModifiedDate;
       this.campaigns = campaigns;
       this.users = users;
       this.custField =  custField;
       this.consent = consent;
       this.checkDoubleOptin = checkDoubleOptin;
       this.custTemplateId = custTemplateId;
    }
   
    public Long getListId() {
        return this.listId;
    }
    
    public void setListId(Long listId) {
        this.listId = listId;
    }
    public String getListName() {
        return this.listName;
    }
    
    public void setListName(String listName) {
        this.listName = listName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getLastStatusChangeDate() {
        return this.lastStatusChangeDate;
    }
    
    public void setLastStatusChangeDate(Date lastStatusChangeDate) {
        this.lastStatusChangeDate = lastStatusChangeDate;
    }
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public boolean isCustField() {
        return this.custField;
    }
    
    public void setCustField(boolean custField) {
        this.custField = custField;
    }
	public boolean isConsent() {
		return consent;
	}
	public void setConsent(boolean consent) {
		this.consent = consent;
	}
   
	public Set getCampaigns() {
        return this.campaigns;
    }
    
    public void setCampaigns(Set campaigns) {
        this.campaigns = campaigns;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

	public Long getSize() {
		return size;
	}
	public void setSize(Long size) {
		this.size = size;
	}
	public Boolean getCheckDoubleOptin() {
		return checkDoubleOptin;
	}
	public void setCheckDoubleOptin(Boolean checkDoubleOptin) {
		this.checkDoubleOptin = checkDoubleOptin;
	}
	public Long getCustTemplateId() {
		return custTemplateId;
	}
	public void setCustTemplateId(Long custTemplateId) {
		this.custTemplateId = custTemplateId;
	}
	
	public Set<EventTrigger> getTriggersSet() {
		return triggersSet;
	}
	public void setTriggersSet(Set<EventTrigger> triggersSet) {
		this.triggersSet = triggersSet;
	}
	
	public Set<EventTrigger> getTriggerSetToBeAddedToMls() {
		return triggerSetToBeAddedToMls;
	}
	public void setTriggerSetToBeAddedToMls(
			Set<EventTrigger> triggerSetToBeAddedToMls) {
		this.triggerSetToBeAddedToMls = triggerSetToBeAddedToMls;
	}
	
	@Override
	public int compareTo(Object o) {
		return 0;
	}
	
	
	
	public String getListType() {
 		return listType;
 	}

 	public void setListType(String listType) {
 		this.listType = listType;
 	}
	public Long getMlBit() {
		return mlBit;
	}
	public void setMlBit(Long mlBit) {
		this.mlBit = mlBit;
	}
 	
 	
}


