package org.mq.captiway.scheduler.beans;
// Generated 24 Jun, 2009 5:18:38 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * Opens generated by hbm2java
 */
@SuppressWarnings({"unchecked","serial"})
public class Opens  implements java.io.Serializable {


     private Long openId;
    // private CampaignSent sentId;
     private Long sentId;
     private Date openDate;
     //private EmailClient emailClient;
     private Long emailClient;

    public Opens() {
    }

    public Opens(Long sentId) {
    	this(sentId, null, null);
    }

    public Opens(Long sentId, Date openDate) {
    	this(sentId, openDate, null);
    }

    public Opens(Long sentId, Date openDate, Long emailClient) {
        this.sentId = sentId;
        this.openDate = openDate;
        this.emailClient = emailClient;
     }

    public Long getOpenId() {
        return this.openId;
    }
    
    public void setOpenId(Long openId) {
        this.openId = openId;
    }
    public Long getSentId() {
        return this.sentId;
    }
    
    public void setSentId(Long sentId) {
        this.sentId = sentId;
    }
    public Date getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

	public Long getEmailClient() {
		return emailClient;
	}

	public void setEmailClient(Long emailClient) {
		this.emailClient = emailClient;
	}

}


